CityOfZion/neo-python

- README.md
Made Venv segment separate from windows installation
> One line change to readme

- neo/Prompt/Commands/Invoke.py
Also needed to reverse any array item when found during iteration of params
> reverse order an array object if found inside of params

- neo/SmartContract/StateReader.py
Reverts CityOfZion/neo-python#26
> Revert "fix Pop() order in Block_GetTransaction and Account_GetBalance"

- neo/Cryptography/Crypto.py
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/Network/NeoNode.py
- neo/Prompt/Commands/LoadSmartContract.py
- neo/SmartContract/ContractParameterContext.py
- prompt.py
- protocol.mainnet.json
- protocol.testnet.json
- Added updates for importing contract addr with n number params.  
- Added updates to user wallet.   
- updated UA string.  
- updated NeoNode functionality
> Weekend Update ™

- prompt.py
Add info about whether we are in TestNet or MainNet to the bottom status bar.
> info about testnet or mainnet in bottom toolbar

- prompt.py
Automatically refresh the bottom bar (block numbers)
> auto-refresh bottom bar (block numbers)

- README.md
- neo/Core/Blockchain.py
- neo/Core/Helper.py
- neo/Core/TX/EnrollmentTransaction.py
- neo/Core/TX/IssueTransaction.py
- neo/Core/TX/PublishTransaction.py
- neo/Core/TX/RegisterTransaction.py
- neo/Core/test_genesis_block.py
- neo/Implementations/Blockchains/LevelDB/test_level_db.py
- neo/Neo.py
- neo/Network/Message.py
- neo/Network/NeoNode.py
- neo/Network/NodeLeader.py
- neo/Network/Payloads/test_payloads.py
- neo/Settings.py
- neo/Utils/VerifiableTestCase.py
- neo/Wallets/Wallet.py
- neo/test_settings.py
- node.py
- prompt.py
- requirements.txt
This is great work from @metachris! Thanks!
To use mainnet, `python prompt.py -m`
To use a specific settings file `python prompt.py --config=path/to/config.json`
> Feature settings

- contrib/README.md
- contrib/privnet-claimall.py
First of hopefully many contributed scripts that neo-python users may find useful. 
This script should ease the setup of private NEO networks for testing, making the initial claim of the 100,000,000 NEO something that can be done entirely from the command-line with no reliance on the neo-gui or Windows.
> contributed script to assist with initial NEO claim from private network

- neo/BigInteger.py
- neo/UInt160.py
- neo/UInt256.py
- neo/UIntBase.py
- neo/test_numbers.py
* Full test coverage for UInt*
* Bugfix (minor) for UInt256
* Moved comparing methods from UInt160 to UIntBase because they work with all UIntBase implementations anyway
> Tests for UInt160, UInt256, minor bugfix and cleanup

- neo/Wallets/KeyPair.py
- neo/Wallets/test_KeyPair.py
- prompt.py
- requirements.txt
- Fixes incorrect error handling in `KeyPair`
- Updates `prompt` to properly catch errors when attempting to import an invalid wif
- Add test cases for coverage
> prompt + KeyPair fixes and test cases

- neo/Settings.py
- neo/Wallets/KeyPair.py
- neo/Wallets/test_KeyPair.py
- prompt.py
- protocol.mainnet.json
- protocol.testnet.json
- requirements.txt
For those of us not running dark background terminals
> Add theme support for prompt

- README.md
- neo/IO/BinaryReader.py
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/SmartContract/ApplicationEngine.py
Fixed the Ubuntu setup instructions in the README. Also fixed a few typos.
Actually installing leveldb and python3.5-dev, and it also needed `pip install wheel`.
Manual testing on Ubuntu.
No
Yes
No
development
> fixed Ubuntu setup instructions in README, and a few typos

- prompt.py
Importing and exporting NEP2 keys from prompt.py
Adding `import nep2 {key}` and `export nep2 {address}`.
Manual testing
No
Yes
I fixed a small thing in `export wif`, so that it requires an address. It would export the wif for all addresses, but without information for which address this is. In `help` it's stated that `export wif {address}` needs an address and probably that's good default behaviour.
Development
> NEP2 import and export in prompt

- contrib/privnet-claim-neo-and-gas.py
I modified `contrib/privnet-claimall.py` to (1) create a wallet and (2) claim some initial GAS.
Using `privnet-claimall.py` and enhancing it.
Manual tests
No
Yes
No
development
> initial contrib/privnet-claim-neo-and-gas.py

- neo/Wallets/Wallet.py
as per @metachris review's request
This was still supposed to be part of #74 but my push was still pending in SourceTree.
> Remove white spaces from docstring endings 

- docs/source/basicusage.rst
- docs/source/contribute.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/overview.rst
- docs/source/prompt.rst
- docs/source/settings-and-logging.rst
- docs/source/smartcontracts.rst
Documentation updates for Settings, logging, smart contract interaction
Adding the documentation
Manual build and check
No
Not applicable
No
development
> Documentation updates: Settings, logging, smart contract interaction

- prompt.py
The load_run command was undocumented in the help output
I added a line documenting usage for load_run
I tested it locally 
No
No
> added help entry for load_run command

- neo/Fixed8.py
- neo/Implementations/Wallets/peewee/Models.py
- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/Implementations/Wallets/peewee/test_user_wallet.py
- neo/Prompt/Commands/Invoke.py
- neo/Prompt/Commands/Send.py
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Utils.py
- neo/Wallets/NEP5Token.py
- prompt.py
- protocol.coz.json
Adds ability to add aliases to addresses, so that they can be used shorthand to remember whats what
Added a model in the UserWallet implementation
manual and automated tests
yes
Not really.  Usage is as follows
```
> wallet alias APRgMZHZubii29UXF9uFa6sohrsYupNAvx awesome
> wallet alias AXjaFSP23Jkbe6Pk9pPGT6NBDs1HVdqaXK cool
> send neo awesome 100
... tx id ...
> wallet tkn_send NEP5 cool awesome 100
...
```
> Feature addr alias

- neo/VM/ExecutionEngine.py
- neo/VM/OpCode.py
Reverts CityOfZion/neo-python#124
This changset should go to `development` first!
> Revert "add array REVERSE and APPEND VMOp codes"

- neo/Core/State/AssetState.py
- neo/IO/BinaryReader.py
- neo/IO/BinaryWriter.py
- neo/IO/Helper.py
- neo/IO/MemoryStream.py
A step forward in addressing #63 
write docstrings
n/a
no
no
> Document all of /neo/IO/

- neo/Wallets/Coin.py
- neo/Wallets/KeyPair.py
- neo/Wallets/NEP5Token.py
- neo/Wallets/Wallet.py
A step forward in addressing #63 
write docs
n/a
no
No
> Document remainder of /neo/Wallets/

- neo/Cryptography/Crypto.py
- neo/Cryptography/Helper.py
- neo/Cryptography/MerkleTree.py
A step forward in addressing #63
write docstrings
run tests.
no
no
> Document /neo/Cryptography/

- neo/Core/State/AccountState.py
- neo/Core/State/AssetState.py
- neo/Core/State/ContractState.py
- neo/Core/State/SpentCoinState.py
- neo/Core/State/StateBase.py
- neo/Core/State/StorageItem.py
- neo/Core/State/StorageKey.py
- neo/Core/State/UnspentCoinState.py
- neo/Core/State/ValidatorState.py
- neo/Core/State/VoteState.py
#63 
write docs
not, only added docstrings. Did not refactor anything.
n/a
no
> Document /neo/Core/State/

- neo/Core/TX/ClaimTransaction.py
- neo/Core/TX/EnrollmentTransaction.py
- neo/Core/TX/InvocationTransaction.py
- neo/Core/TX/IssueTransaction.py
- neo/Core/TX/MinerTransaction.py
- neo/Core/TX/PublishTransaction.py
- neo/Core/TX/RegisterTransaction.py
- neo/Core/TX/Transaction.py
- neo/Core/TX/TransactionAttribute.py
#63 
write docs
not. only added docstrings. didn't refactor anything
no, n/a
yes, see my comment below about a reference that was required.
> Document /neo/Core/TX/

- neo/Core/AssetType.py
- neo/Core/Block.py
- neo/Core/BlockBase.py
- neo/Core/Blockchain.py
- neo/Core/CoinReference.py
- neo/Core/FunctionCode.py
- neo/Core/Header.py
- neo/Core/Helper.py
Address #63 
write docs
ran tests
no
no
> Document /neo/Core/

- neo/Network/IPEndpoint.py
- neo/Network/Inventory.py
- neo/Network/InventoryType.py
- neo/Network/Message.py
- neo/Network/NeoNode.py
- neo/Network/NodeLeader.py
- neo/Network/Payloads/AddrPayload.py
- neo/Network/Payloads/GetBlocksPayload.py
- neo/Network/Payloads/HeadersPayload.py
- neo/Network/Payloads/InvPayload.py
- neo/Network/Payloads/NetworkAddressWithTime.py
- neo/Network/Payloads/VersionPayload.py
address #63 
write write
ran unittests
no
no
> Document /neo/Network/ & /neo/Network/Payload/

- README.md
> Fixes setup docs for CentOS

- Makefile
- README.md
Adds a Makefile with a few useful commands:
* make lint
* make test
* make coverage
* make docs
n/a
Manual tests
no
no
> Added makefile with a few useful commands

- prompt.py
The `prompt.py` responses were a bit inconsistent (casing, spacing etc.). This PR makes it a bit more consistent.
Adhere to PEP8 and the CoZ coding style used in other files.
No functional change.
No.
No.
> Improve prompt.py style

- README.md
The current Getting Started documentation was a bit confusing for beginners (especially to me as one). The Python 3.5 part was very thin, plus figuring out exactly what it is and how it compares to the other projects in the ecosystem took some time.
I revised the whole Getting Started documentation, hopefully making it clearer and more concrete.
I followed the steps to setup my own environment.
Unfortunately, no tests for documentation.
I refactored the documentation of "how to release", that's probably something you should double …
> Getting Started update

- neo/api/JSONRPC/JsonRpcApi.py
- neo/api/JSONRPC/test_json_rpc_api.py
Fix params parsing & getblockcount method
add getblockhash example
parsed `params` with `ast`.
write tests
tests
yes
no
> Fix params parsing & getblockcount method

- neo/Core/State/AccountState.py
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/api/JSONRPC/JsonRpcApi.py
- neo/api/JSONRPC/test_json_rpc_api.py
- added a few method implementations to the JSONRPC server
- added in placeholders for all other methods listed in C# implementation
code
tests
yes
no
> Implementing a few methods

- neo/api/JSONRPC/neo-cli-json-rpc-docs.md
- neo/api/JSONRPC/test_json_rpc_api.py
add edge case tests
write tests
tests
yes
no
> add `getblocksysfee` error test cases

- .github/PULL_REQUEST_TEMPLATE.md
Added two questions to the PR template:
* Did you run `make lint` and `make test`?
* Are you making a PR to a feature branch or development rather than master?
> Update PR template: target branch and make lint+test

- docs/source/install.rst
Just a small addition to the troubleshooting docs.
See also #205
> Troubleshooting docs: osx scrypt

- prompt.py
the help message for `wallet tkn_mint` was unintuitive. 
it suggested you could run a command like the following (which will actually fail):
> wallet tkn_mint PCG1 AZQyxPDwXhiNyvzXx6sLyW1LcbotpeQjp1 0 0.1
update the help msg
-
no
no
no
dev
> clarify help message for tkn_mint command

- README.md
- docs/source/index.rst
- docs/source/installwindows.rst
- prompt.py
It adds installation instructions and a small change in prompt.py
There was a bunch of problems and I included the solutions to all of them
I tested by myself
No
Not really
No
To development
> Windows support

- neo/contrib/smartcontract.py
@on_storage and @on_execution events were not working.
Added support for wildcard event type matching.
Tested it. Didn't work before, but works now :)
No.
No.
Yes.
development
> Wildcard SmartContract events

- .github/PULL_REQUEST_TEMPLATE.md
Added a line to the PR template about adding something to CHANGELOG
> PR template update: please add to changelog

- neo/SmartContract/ContractParameterContext.py
Bugfix for `neo/SmartContract/ContractParameterContext`
Use new code from @localhuman 
Manual and auto tests
no
no
yes
dev
> Bugfix for neo/SmartContract/ContractParameterContext

- .travis.yml
- Makefile
- neo/Settings.py
- prompt.py
Making it easier to use coznet
* Settings update: `is_coznet`, `net_name()`, `setup_coznet()`
* prompt update: `--coznet` argument, exclusive network argument group
Manual tests
No
No
Yes
development
> Added easy CoZ net support

- neo/Core/VerificationCode.py
- neo/Prompt/Commands/BuildNRun.py
- neo/Prompt/Commands/Invoke.py
- neo/Prompt/Commands/Send.py
- neo/Prompt/Commands/Tokens.py
- neo/SmartContract/Contract.py
- neo/Wallets/Wallet.py
- prompt.py
- newly created wallets had an issue syncing, so nothing would show up in `synced balances`.  this is fixed
- with new wallet encryption, some commands in prompt were not properly encoding the password and giving an 'incorrect password' error. this is fixed.
- also removed 'try .. catch' blocks for `BuildAndRun` command so that exceptions aren't swallowed and missed
- code
- running tests
- fixed tests
- not really
- yes
**Are you making a PR to a feature branch or development rather than …
> Bug wallet sync bug password error

- prompt.py
neo> export wif AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y
[wallet password]> ***************
Could not execute command: 'PromptInterface' object has no attribute 'wallet'
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 882, in _bootstrap
self._bootstrap_inner()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/Users/mphilips/dev/neo-tutorial/neo-python/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
task()
File …
> Fix attribute typo from wallet to Wallet

- README.md
- docs/source/installwindows.rst
Minimal update for Windows docs: link to the guide about setting up the linux subsystem
> windows docs: link to linux subsystem setup

- examples/json-rpc-api-server.py
- neo/api/JSONRPC/JsonRpcApi.py
- neo/api/utils.py
* write a PID file, so it is easy to kill from a service
* Continuously print block heights
* Added CORS headers to the response
* Example systemd service config file
Testing
No
> Updated examples/json-rpc-api-server.py

- README.md
Just added info about bootstrapping and Docker to the README.
> README update: bootstrap and Docker

- CHANGELOG.rst
- neo/SmartContract/ContractParameter.py
- neo/SmartContract/ContractParameterType.py
- neo/VM/VMState.py
- neo/api/JSONRPC/JsonRpcApi.py
- neo/api/JSONRPC/test_json_invoke_rpc_api.py
Fixes JSON-RPC output issues from #233.
Implemented appropriate fixes for each of the issues raised.
Tested JSON-RPC output and updated existing tests to account for new formats.
No.
> JSON-RPC output fixes

- api-server.py
Fixes and improvements for #283.
Fixed issues and deployed to one of our nodes.
Tested on deployed node.
No.
> API Server tweaks

- api-server.py
- requirements.txt
Updated api server with updates from https://github.com/CityOfZion/neo-python/pull/281 by @brianlenz and more customized and simplified logging setup.
> Api server logging updates

- docs/source/conf.py
- docs/source/neo/SmartContract/smartcontracts.rst
clean up docs
write
run `make docs`
n/a
I assume this PR does not require updating changelog.rst, it's too small to mention imho
> just some docs polishing

- CHANGELOG.rst
- prompt.py
Added `-v/--verbose` argument to `prompt.py`: show sc-events
Add flag in prompt.py
Manual tests
No
> prompt.py -v/--verbose argument: show sc-events

- neo/Settings.py
- neo/SmartContract/StateReader.py
- neo/SmartContract/tests/sc_debug_events.py
- neo/SmartContract/tests/test_sc_debug_events.py
- neo/VM/ExecutionEngine.py
- prompt.py
The following was discussed on discord, this implements the first 2 items, and I can push the 3rd item to this PR once we agree on the implementation of 1+2.
> During the dApp competition i made some local changes to make debugging smart contracts easier and I'm thinking about what can/should flow back. Would love some input on the following ideas;
> 
> 1) add instruction counter to the error message/stacktrace. 
> Rationale: it allows for setting a conditional breakpoint exactly on the instruction that's going to fail next. The counter also gives some indication whether it failed early during execution or later on (giving a feel how deep the error lays). 
> 
> 2) add a debug toggle to emit Notify events even if …
> Sc debug improvements

- api-server.py
- requirements.txt
Changes custom syslog implementation to use logzero 1.5.0's native syslog support.
Updated to logzero 1.5.0 and updated the integration accordingly.
Tested it.
No.
> Logzero syslog support

- CHANGELOG.rst
this was supposed to be part of #294 
add description to changelog
run `make docs`
no
> SS debug improvements (changelog update)

- CHANGELOG.rst
- neo/Settings.py
- prompt.py
When people do a `git pull`, they often get cryptic error messages. This PR adds a dependency check to verify that all required dependencies are those actually installed.
Test
No
> Settings.check_dependencies to verify dependencies

- setup.py
Fixes `` FileNotFoundError: [Errno 2] No such file or directory: 'README.md'``
> Fix error no such file README.md

- .travis.yml
That was painful :P
I think the main reason for the problems were special characters in the docker password.
Edit: Now I've added the DOCKER_USER and DOCKER_PASS in the Travis-CI settings, with quotes ^^
> Finally, fixed the Docker auto deploys on new releases/tags

- CHANGELOG.rst
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Network/NeoNode.py
- neo/VM/ExecutionEngine.py
- neo/bin/prompt.py
fix for current block height lag behind other RPC implementations by 1-3 blocks
- addresses #344 
- always ask for more headers
- if you only get one header, ask for the corresponding block right away
- ran tests
- no
> Block Height fixes

- README.rst
- docs/source/license.rst
Updated readme with contributors
> Readme contributors

- CHANGELOG.rst
- LICENSE.md
- neo/VM/ExecutionEngine.py
- neo/data/protocol.mainnet.json
cc: @ixje 
Excessive CPU usage on RPC nodes: #352 
Note that this only helps avoid some unnecessary calls, but it doesn't solve the CPU load issue entirely.
Removed unnecessary calls to `write_log` and `ToName`.
Profiled performance before and after over a similar time period. The number of invocations reduced from 130k to 9.
No.
> VM Engine Performance Improvements

- CHANGELOG.rst
- neo/Prompt/Commands/Invoke.py
- neo/VM/ExecutionContext.py
- neo/VM/ExecutionEngine.py
- fixes #387 
- debug maps are added to the ExecutionEngine with a script hash pair.
- tests
- no 
> Debugger Fixes ( #387 )

- CHANGELOG.rst
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Prompt/Commands/Invoke.py
- neo/VM/InteropService.py
- fixes #393 
- remove extra `storage.commit()` from `LevelDBBlockchain`
- manual testing, resyncing chain
- no 
> Feature commit db changes

- CHANGELOG.rst
- requirements.txt
Update to neo-python-core 0.4.1 pypi.python.org/pypi/neocore
Update requirements.txt
Test
No. Perhaps that this version of neocore also introduces the cli command `np-utils`, which currently doesn't do much besides converting some datatypes: https://github.com/CityOfZion/neo-python-core/blob/master/neocore/bin/cli.py
> Neocore 0.4.2

- neo/SmartContract/StateMachine.py
Log DELETE storage even when key storage is not 20
> Fix STORAGE_DELETE logs

- neo/Core/FunctionCode.py
When trying to reproduce issue #217, I've imported a smart contract that contained values that caused the generated block to produce this error on my `neo-python` node:
```
neo> [I 180517 15:05:58 LevelDBBlockchain:842] Could not persist block bytes must be in range(0, 256) 
Unhandled error in Deferred:
```
and more detailed:
```
File "/home/user/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 838, in PersistBlocks
self.Persist(block)
File "/home/user/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 805, in Persist
contracts.Commit(wb)
File "/home/user/neo-python/neo/Implementations/Blockchains/LevelDB/DBCollection.py", line 65, in Commit …
```
> Fix error with invalid return-types 

- CHANGELOG.rst
- neo/Core/Block.py
- neo/Core/Blockchain.py
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Settings.py
- neo/bin/export.py
- neo/bin/import.py
- setup.py
- features for #441 
- added `np-import` and `np-export` commands 
- manual tests
usage: 
- `np-export -m --output chain.pcc`
- `np-import -m --input chain.pcc`
- also use flag `-l` for import to display smart contract events
> Feature import export

- CHANGELOG.rst
- neo/data/protocol.mainnet.json
Used new bootstrap files that @localhuman posted in discord.
Changing the mainnet protocol file.
Manual test
No
> Updated MainNet bootstrap files

- neo/bin/import.py
the new blockchain `import` was apparently slow. The changes introduced give a 2x improvement
re-use objects instead of re-creating them for each block to process.
manual testing
no
can I skip for this one? pretty please 🙏
> speed up import by re-using stream and block objects

- CHANGELOG.rst
- neo/Network/NodeLeader.py
- neo/Network/test_node_leader.py
- neo/SmartContract/ApplicationEngine.py
- neo/Wallets/test_KeyPair.py
- neo/bin/prompt.py
- neo/data/protocol.mainnet.json
- When the number of connected peers falls to 2, the NodeLeader restarts.  
- Change `logger.error` when application has run out of gas to `logger.debug`
- updated seed list
> Min nodes change

- neo/bin/prompt.py
- requirements.txt
Reverts CityOfZion/neo-python#477
> Revert "Dependency update: prompt-toolkit"

- neo/bin/prompt.py
- requirements.txt
Continuation of #477 with a fix for the `<prompt_toolkit.styles.style.Style object at 0x10fc36f60>` prints.
https://github.com/CityOfZion/neo-python/commit/4d9f6c60b225061d56c6c01106559629623a1169
Manual tests
No, except the changed bottom toolbar styling. see #477 
> Dependency update: prompt-toolkit

- neo/bin/prompt.py
prompt-toolkit v2 changed how to use `prompt(..)`. this PR fixes the problems with #487 
assigning `session.prompt` to `self.prompt`
manual tests
no
> Fix prompt() calls, especially for asking for passwords

- CHANGELOG.rst
- requirements.txt
- updates neo-boa and neo-core
> requirement updates

- CHANGELOG.rst
- neo/Core/TX/Transaction.py
- neo/Prompt/Commands/Invoke.py
- neo/Prompt/Commands/Send.py
- neo/Prompt/Commands/Tokens.py
- neo/Prompt/Utils.py
- neo/Wallets/NEP5Token.py
- neo/bin/prompt.py
Fix https://github.com/CityOfZion/neo-python/issues/445
transaction attributes were parsed but not added to Invocation transactions. 
Manual testing on privatenet
see own review
> Fix sending NEP5 tokens from multisig address

- CHANGELOG.rst
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
- neo/bin/prompt.py
Adds CreateAddress Feature
Referenced neo-cli and talked with @ixje 
Testing on my own privatenet and created a test for it.
no.
> Adding CreateAddress Feature

- .travis.yml
Resolve #510 
enable caching
not, pushing here will tell me if travis agrees
no
> enable fixture and pip caching

- CHANGELOG.rst
- neo/data/protocol.mainnet.json
- neo/data/protocol.testnet.json
- updates mainnet and testnet bootstraps
> Feature update bootstrap

- neo/Prompt/Commands/Invoke.py
- neo/Prompt/Commands/Send.py
- neo/bin/prompt.py
fix for sending from address with multiple owners, fix spelling issue, help issue
> Minor updates

- CHANGELOG.rst
- neo/Core/CoinReference.py
Fix #575 
use `To0xString()` instead of `ToString()`
manual
no
> Update vins JSON output format

- neo/SmartContract/ApplicationEngine.py
- neo/SmartContract/tests/test_unclosed_while_loop.py
- Code cleanup via suggestions here: https://github.com/CityOfZion/neo-python/pull/581#issuecomment-417037236
> Cleanup max testops

- CHANGELOG.rst
- neo/Core/Blockchain.py
- neo/Core/Helper.py
- neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
- neo/Implementations/Blockchains/LevelDB/TestLevelDBBlockchain.py
- neo/Prompt/Commands/BuildNRun.py
- neo/Prompt/Commands/Invoke.py
- neo/Prompt/vm_debugger.py
- neo/SmartContract/ApplicationEngine.py
- neo/SmartContract/Iterable/test_interop_iterable.py
- neo/SmartContract/StateMachine.py
- neo/SmartContract/StateReader.py
- neo/SmartContract/tests/test_app_engine.py
- neo/VM/ExecutionContext.py
- neo/VM/ExecutionEngine.py
- neo/VM/InteropService.py
- neo/VM/OpCode.py
- neo/VM/RandomAccessStack.py
- neo/VM/VMFault.py
- neo/VM/tests/test_execution_engine.py
- neo/VM/tests/test_interop_blockchain.py
- neo/VM/tests/test_interop_map.py
- neo/VM/tests/test_interop_serialize.py
- neo/Wallets/NEP5Token.py
- neo/api/JSONRPC/JsonRpcApi.py
Fix https://github.com/CityOfZion/neo-python/issues/585
also includes the required commits:
https://github.com/neo-project/neo/commit/0de8b8867326405265e3daa24128269e33d914de
https://github.com/neo-project/neo-vm/commit/59f3e664a04f66c4d455d40db7bc718321264aa9
https://github.com/neo-project/neo/commit/e8c5e03bb7ce4ea7548c5d32ab2b0d985b8fdbd9
https://github.com/neo-project/neo/commit/b8ad89e285c566203e0139f601ac85fc2b536299
https://github.com/neo-project/neo/commit/8ba66e58466586c906bb893ae00a33a5935742dc
https://github.com/neo-project/neo/commit/96606306a4275686db0aae9af475f1e074e2b5e2
https://github.com/neo-project/neo/commit/5894cbd7c24c12fb7d181c134bfe1e7d3664e2e4
write code …
> Add stack isolation

- neo/data/protocol.mainnet.json
- Updated mainnet chain and notification data bootstrap files.
> Bootstrap update

- README.rst
- setup.py
readme information was slightly outdated. 
updated texxt
n/a
no
> Update readme and setup info

- CHANGELOG.rst
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_claim_command.py
Fix https://github.com/CityOfZion/neo-python/issues/653 needed for https://github.com/CityOfZion/neo-privatenet-docker/pull/54
make sure all `return` paths return a tuple
make test
no
> Fix return types of claimGas function

- examples/build_raw_transactions.py
The previous example code was 99% complete but used fake data from neoscan. The update uses data from the `neo-python-privnet-unittest` network which allows people to validate the result against the docker image.
update values and add missing statement to get correct raw output string.
manually tested against docker image according to instructions written in the comment of the file
no
> Update build raw TX examples

- neo/data/protocol.mainnet.json
Fix #682 
upload new bootstrap files. Thanks to @jseagrave21 for making the latest available (i was behind on syncing)
wget && `python neo/bin/bootstrap.py -n -m`
no
> Update Mainnet bootstrap files (chain + notif)

- CHANGELOG.rst
- docs/source/neo/SmartContract/smartcontracts.rst
As pointed out by a user in this comment https://github.com/CityOfZion/neo-python/issues/683#issuecomment-433456746
the documentation is behind for the newly included `IsPayable` flag
update docs
`make docs`
no
> Update docs for IsPayable flag

- neo/bin/bootstrap.py
destination dir was not dynamic
> quick bootstrap dir fix

- README.rst
- neo/VM/InteropService.py
Super minor, was reading through the code and saw some added white space and what looked like part of a comment that had been forgotten to be erased.
> Removed some white space and hash

- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
- neo/Wallets/Wallet.py
Migrate the command `wallet rebuild` to the new Command system.
Implementation of `CommandWalletRebuild` and small refactoring of `Wallet.Rebuild()`.
Added unit tests.
Manual testing
No.
> Implement CommandWalletRebuild

- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/Prompt/Commands/Wallet.py
remove deprecated migrate command
remove code
> remove migrate command

- neo/Prompt/CommandBase.py
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_claim_command.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
DO NOT MERGE AS IS.
Migrate the command `wallet claim` to the new Command system.
Implementation of `CommandWalletClaimGas`.
Added unit tests.
There are 2 tests failing for an unknown reason, I will add comments directly in the code.
> [refactor-prompt] Implement CommandWalletClaimGas

- neo/Implementations/Wallets/peewee/UserWallet.py
- neo/Prompt/Commands/Send.py
- neo/Prompt/Commands/Tokens.py
- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_token_commands.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
Moves implementation of #623 forward by implementing the base command for `wallet token` and implementing the subcommand `wallet token delete`
Write code
write tests
> [refactor-prompt] Add wallet token base + delete

- neo/Prompt/Commands/Wallet.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
move #623 forward by adding `wallet import nep` and `wallet import wif` commands
write code
make test
no
> [refactor-prompt] add wallet import nep2/wif

- neo/Prompt/Commands/Tokens.py
- neo/Prompt/Commands/tests/test_token_commands.py
move #623 forward, add `wallet token mint`
migrate, write code
make test
no
> [refactor-prompt] add token mint

- docs/source/neo/SmartContract/application-vs-verification.rst
- docs/source/neo/SmartContract/smartcontracts.rst
- neo/Wallets/Wallet.py
- neo/api/JSONRPC/test_json_rpc_api.py
Fixed a few typos seen while reading the docs
> A few minor typo fixes

- neo/Prompt/Commands/LoadSmartContract.py
- neo/Prompt/Commands/SC.py
- neo/Prompt/Commands/tests/test_loadsmartcontract.py
- neo/Prompt/Commands/tests/test_sc_commands.py
- neo/Prompt/Utils.py
- neo/Settings.py
move #623 forward by porting `import contract` to `sc deploy`
port & write code + tests
make tests
no
> [refactor-prompt] add sc deploy

- neo/Prompt/Commands/SC.py
- neo/Prompt/Commands/tests/test_sc_commands.py
move #623 forward. Add the final command `sc invoke` (formerly known as `testinvoke`)
port code
make test
no
> [refactor-prompt] add sc invoke

- neo/Prompt/Commands/Send.py
The `--from-addr` description of `wallet send` and `wallet sendmany` cleverly describes a default address if not specified
```
source address to take funds from (if not specified, take first address in wallet)
```
While technically it takes the first address, from a user perspective it does not always equal to the first address seen when using the `wallet` command. The discussion in #605 and the debugging session that followed led to this discovery. This means we already have a real world  use-case where this is a problem.
The PR is made to the `refactor-prompt` branch instead of `development` (where it also applies) because otherwise we'd have to migrate the solution again once we merge the `refactor-prompt` …
> [refactor-prompt] Improve send/sendmany feedback, fix default address usage

- CHANGELOG.rst
cleanup changelog for release by adding all PR links and order them by PR number
> Cleanup changelog

- neo/Prompt/Commands/tests/test_claim_command.py
- neo/Prompt/Commands/tests/test_config_commands.py
- neo/Prompt/Commands/tests/test_output_config.py
- neo/Prompt/Commands/tests/test_sc_commands.py
- neo/Prompt/Commands/tests/test_search_commands.py
- neo/Prompt/Commands/tests/test_send_commands.py
- neo/Prompt/Commands/tests/test_show_commands.py
- neo/Prompt/Commands/tests/test_token_commands.py
- neo/Prompt/Commands/tests/test_wallet_commands.py
> Cleanup commented code in tests

- neo/SmartContract/Contract.py
will be removed from neocore here: https://github.com/CityOfZion/neo-python-core/pull/170
> remove bitcoin imported function 

- neo/VM/ExecutionEngine.py
- neo/VM/InteropService.py
Update to support
https://github.com/neo-project/neo-vm/pull/91
write code
run test vectors
> Add VM ARRAY/STRUCT conversion

- neo/bin/api_server.py
fix #917 
followed solution by hal
> resolve high cpu usage api_server

- CHANGELOG.rst
- neo/Core/Block.py
- neo/Core/CoinReference.py
- neo/Core/Header.py
- neo/Core/TX/Transaction.py
- neo/SmartContract/Contract.py
- neo/SmartContract/StateReader.py
- neo/VM/ExecutionEngine.py
- neo/VM/InteropService.py
- neo/VM/tests/test_interop_serialize.py
- neo/Wallets/Coin.py
close #1000
implemented "reference" to self checking
audit of mentioned testnet block now passes
no
> Fix max recursion for certain stackitem setups

- neo/Prompt/Commands/Bootstrap.py
- neo/bin/import_blocks.py
fix #984 for release plus some minor cleanup
> fix #984 + cleanup

- .travis.yml
- requirements.txt
> update requirements and travis

- docs/source/overview.rst
Current documentation is not very user friendly
I reviewed it with @lock9, changed some texts and fixed one broken link. 
I have little background in this area, I tried to make it more simple for starters (with @lock9 help).
No
How can I add it to changelog? Should I create a new version?
> Review of 'Overview' documentation section
