CityOfZion/neo-python

Dockerfile
Using this file, the client can be set up more easily. Having Docker installed, it is just "docker build . -t neo-python" from the main directory of the repository and "docker run -it neo-python" to start the client.
=> Dockerfile with Python client and dependencies

neo/SmartContract/StateReader.py
Uncovered these issues when attempting to execute the mintTokens operation in the ICO template code from the neo-project csharp-examples.
=> Fixed bug in Transaction_GetReferences, case issues and missing return

neo/Prompt/Commands/Invoke.py
neo-gui puts the array length on the end of the array, followed by a PACK opcode. Making this change allows the VM to properly import the array values into the stack for the contract execution.
=> put array length and PACK at end of array

neo/IO/BinaryReader.py
ReadFloat should read 4 byte and ReadDouble should read 8 byte.
=> Fix ReadFloat and ReadDouble in BinaryReader

neo/VM/ExecutionEngine.py
Fix to get correct return from SUBSTR opcode (bytearray slice operation needed start:end instead of start:length)
=> fix for bytearray slice end calculation for SUBSTR opcode

prompt.py
The help for testinvoke had an extra "contract" keyword that didn't reflect the actual command syntax
=> removed unused keyword "contract" from testinvoke in help output

neo/VM/ExecutionEngine.py, neo/VM/OpCode.py
Two new opcodes for exception handling were added to neo-vm on Aug 22, causing transactions with multiple invocations in neo-python's implementation to halt execution after the first invocation due to the trailing unknown opcode
=> added THROW and THROWIFNOT opcodes to engine

neo/Prompt/Commands/Invoke.py
When contract test invoke is not successful, got error message ValueError: not enough values to unpack (expected 4, got 2)
=> Not enough values to unpack (expected 4, got 2)

neo/SmartContract/StateReader.py
Block_GetTransaction and Account_GetBalance both pop their arguments off the stack in the wrong order. This is also a problem in the core Neo code, and I have submitted PR #83 in that repository to fix the issue there as well.
=> fix Pop() order in Block_GetTransaction and Account_GetBalance

neo/Implementations/Wallets/peewee/UserWallet.py
When using the `create wallet` command, if there is an existing wallet already open it will become permanently corrupted instead of a new database file being created. 
Because the database instance already exists, the code will currently write the new keypair into the existing file and overwrite the master key, causing the wallet to no longer be decryptable and throwing an exception any time it is opened again. 
This change will force any existing wallet database instance to be closed before creating a new one.
=> close existing wallet before creating new one

boa/code/builtins.py, boa/code/vmtoken.py, boa/tests/src/TakeTest.py
First foray into trying to implement builtins into compiler, started with take() since it was already fleshed out in builtins.py. Test case seems to work:
`
neo> build boa/tests/src/TakeTest.py test 05 05 False
Saved output to boa/tests/src/TakeTest.avm 
-----------------------------------------------------------
Calling boa/tests/src/TakeTest.py with arguments [] 
Test deploy invoke successful
Used total of 38 operations 
Result b'hello' 
Invoke TX gas cost: 0.001 
`
=> completed implementation of take() builtin

neo/Core/TX/Transaction.py, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Prompt/Commands/LoadSmartContract.py, neo/Prompt/Commands/Send.py, neo/SmartContract/Contract.py, neo/SmartContract/ContractParameterContext.py, neo/SmartContract/ContractParameterType.py, neo/VM/ExecutionEngine.py, prompt.py
This pull request implements multi-signature capability that is compatible with the latest neo-gui, i.e. you can begin a multi-sig transaction in either neo-python or neo-gui, then import and sign/relay the resulting JSON-serialized transaction in either client. 
This should allow people with private networks to claim all the NEO and GAS from the initial contract without having to use Windows at all.
=> implemented multi-sig capability

.gitignore, prompt.py
When in the prompt users press CTRL + D, it threw an Exception before. Added an exception handler to quit the prompt.
This solution is recommended in the prompt-toolkit example here: https://github.com/jonathanslenders/python-prompt-toolkit/tree/master/examples/tutorial
=> prompt.py: Allow quitting with CTRL-D. Before it threw an exception.

README.md
Python is a brand name, so it should be capitalized. In the documentation, NEO is most of the time written with full caps, so I changed the NEO spelling in this doc as well. Added link to CoZ Youtube for ease of use. Removed an excess space.
=> Improve layout and spelling

neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
Users have reported occasional exceptions with leveldb code reporting `binascii.Error: Non-hexadecimal digit found` when restarting neo-python after a hard exit. This seems to occur in the code block starting with the `if` statement on line 150 of LevelDBBlockchain.py. This code is only executed if the database is opened in a state where it has been initialized with the genesis block but has not downloaded any headers from remote nodes yet.
Line 153 retrieves a value that is prefixed with a `long` encoded as a bytearray, followed by hex-encoded data. The code was treating the `long` as 4 bytes instead of 8 (as it is coded on line 531 when the data is stored), leading to the binascii module trying to decode 4 bytes of non-hexencoded data, leading to the exception.
=> fix for non-hexadecimal digit found error in leveldb

README.md, neo/Core/Blockchain.py, neo/Core/Helper.py, neo/Core/TX/EnrollmentTransaction.py, neo/Core/TX/IssueTransaction.py, neo/Core/TX/PublishTransaction.py, neo/Core/TX/RegisterTransaction.py, neo/Core/test_genesis_block.py, neo/Implementations/Blockchains/LevelDB/test_level_db.py, neo/Neo.py, neo/Network/Message.py, neo/Network/NeoNode.py, neo/Network/NodeLeader.py, neo/Network/Payloads/test_payloads.py, neo/Settings.py, neo/Utils/VerifiableTestCase.py, neo/Wallets/Wallet.py, neo/test_settings.py, node.py, prompt.py
Allows to switch between mainnet and testnet with cli arguments. Might also be useful for further settings in the future.
Several files were touched, but mainly just the import changed from `from neo import Settings` to `from neo.Settings import settings`. The real changes are using a class in [Settings.py](https://github.com/metachris/neo-python/blob/c9585355cfe275bc2aa528e01dd8f28ac6b53880/neo/Settings.py), and adding cli args to [prompt.py](https://github.com/metachris/neo-python/commit/c9585355cfe275bc2aa528e01dd8f28ac6b53880#diff-51c9e721b63b4d4727f5d7f5423a5017).
=> Settings which are dynamically configurable

neo/UInt160.py, neo/UInt256.py, neo/UIntBase.py, neo/test_numbers.py
* Fixed an error in `UIntBase.__eq__`, where it compares `type(self)` to `type(self)`: https://github.com/CityOfZion/neo-python/blob/905775fa5abb7efd1fa6877188eb09410bbebdc0/neo/UIntBase.py#L64
* Added tests for full coverage of `UIntBase`
* Minor cleanup: mostly removal of extra empty lines
=> UIntBase: __eq__ bugfix, tests and cleanup

contrib/privnet-claimall.py, neo/SmartContract/ContractParameterContext.py
The added check for self.isMultiSig under ContractParametersContext broke the privnet-claimall script since I wasn't passing isMultiSig=True when creating the context. This fix addresses that and also an issue finding the module paths when running the script from inside the contrib directory.
=> fix for multi-sig context returning complete after one signature

protocol.privnet.json
Added a `protocol.privnet.json`. Not sure if you want, but I guessed its useful to possibly a large enough part of the user-base to warrant a third file besides mainnet and testnet configs. Any thoughts?
=> Added protocol.privnet.json

prompt.py
If there is a file-error when creating a wallet, the code should not continue
=> prompt: create wallet with file error should not continue

.gitignore, neo/Implementations/Wallets/peewee/Models.py, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/Withdraw.py, neo/Prompt/Utils.py, neo/SmartContract/ApplicationEngine.py, neo/VM/ScriptBuilder.py, neo/Wallets/NEP5Token.py, neo/Wallets/Wallet.py, prompt.py, protocol.testnet.json
Adds wallet support for interacting with NEP5 compliant tokens.
To use, add the script hash of an NEP5 compliant token: 
`import token f8d448b227991cf07cb96a6f9c0322437f1599b9`
The balance and details of the token will now appear when using the `wallet` command, along with token details such as this.  The `symbol` listed below will be used in following commands.
```
"tokens": [
{
"symbol": "NEP5",
"decimals": 8,
"contract address": "AYhE3Svuqdfh1RtzvE8hUhNR7HSpaSDFQg",
"name": "NEP5 Standard",
"script_hash": "f8d448b227991cf07cb96a6f9c0322437f1599b9"
}
]
```
To send tokens from your address:
`wallet tkn_send {TOKEN_SYMBOL} {FROM_ADDR} {TO_ADDR} {AMOUNT}`
The NEP5 methods `transferFrom`, `approve`, and `allowance` …
=> Feature nep5 wallet

neo/Utils/BlockchainFixtureTestCase.py
When the fixture download failed, the partially downloaded fixture file is left over, but the tests cannot run on them and we got many confusing error messages from the tests.
This commit just aborts running the tests if there is a defect fixtures file, and gives a hint on how you might solve it.
Raising an Exception when the fixtures file is corrupt.
Manual tests
No
Yes
No
development
=> fixture download: improved error handling

neo/Network/NeoNode.py
Do not merge yet, long-running tests are currently in progress.
Edit: Several instances of this code (on mainnet and testnet) have been running for about 8 hours now without problems. I'll leave it running overnight and report back tomorrow morning.
It may be easier to get an overview of the changes by looking at the updated `CheckDataReceived` method: https://github.com/metachris/neo-python/blob/2d5023732ef219f6ecd30b50e4f1d2e5f22b5db8/neo/Network/NeoNode.py#L107
NeoNode ran into an issue which caused the maximum recursion depth do be reached (`Could not check message data maximum recursion depth exceeded while calling a Python object`). See #59 
The reason was a ping-pong …
=> NeoNode bugfix: maximum recursion depth (fixes #59)

neo/Settings.py
When importing neo from outside the root directory, some imports complained that the settings JSON files could not be found.
Making them absolute
Manual tests
No
Yes
No
development
=> Settings: fix relative path references by making them absolute

neo/Cryptography/Helper.py, neo/Cryptography/test_crypto.py, neo/Wallets/KeyPair.py, neo/Wallets/test_KeyPair.py, requirements.txt
Added NEP2 encrypted key support to KeyPair. See #65
Adding NEP2 encrypted key support to KeyPair. @ixje helped with testing and finalizing the solution.
Tests
Yes
Yes
No
development
=> NEP2 Support for KeyPair (fixes #65)

neo/Core/Blockchain.py, neo/EventHub.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Implementations/Blockchains/LevelDB/TestLevelDBBlockchain.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Notify.py, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/StateMachine.py, neo/SmartContract/StateReader.py, neo/VM/ExecutionEngine.py, neo/VM/InteropService.py, neo/Wallets/NEP5Token.py
- Added `execution_success` to `SmartContractEvent`, so that `Notify` events can have this context for when they are being processed
- Moved dispatch of `Notify` to occur after execution of the contract, and include the `execution_success` in the event
Notes: Ideally, when dispatching the events we'd be passing around `UInt160` or `UInt256` for tx hash or for contract hashes, that way any service consuming the events will have a flexible data type to use
=> Feature events localhuman

neo/Prompt/Commands/tests/test_wallet_commands.py, neo/Wallets/Wallet.py
Added `Wallet.GetSyncedBalances()` to easily get a list of fully synced balances. External dApps often need a way to know the current wallet balances.
The code is basically reused from the `ToJson()` method.
Any feedback whether it would be better to return an object with asset name as key and balance as value, or keep the list style like now would be appreciated.
n/a
Manual and automated tests
Yes
yes
No
development
=> Added Wallet.GetSyncedBalances

neo/EventHub.py, neo/Settings.py, requirements.txt
Flexible logging in general, and smart-contract events in particular, with configuration through `neo.Settings`. Implements [logzero](https://logzero.readthedocs.io/en/latest/#example-usage) to simplify logging from anywhere in the project.
In Settings you can now:
* enable/disable logging smart contract events with `settings.log_smart_contract_events(..)`
* Setup a (rotating) logfile with `settings.logfile(..)`
Anywhere in the code you can do `from logzero import logger` and then use it like `logger.info(..)`, `logger.debug(..)`, `logger.exception(..)`, etc. If a logfile was setup through the settings, all those log statements will also be written to the logfile.
Note: with this approach, we could replace the …
=> Logging: configure through settings, enable (rotating) logfile

setup.py
Minor fix to `setup.py`: set `python_requires='>=3.4, <3.6'`
n/a
n/a
no
no
=> setup.py: set python_requires='>=3.4, <3.6'

neo/Wallets/Wallet.py, neo/Wallets/test_wallet.py
Wallet.ContainsKey was not working
Change the `unhex` parameter to match [this](https://github.com/CityOfZion/neo-python/blob/master/neo/Wallets/KeyPair.py#L81)
```self.PublicKeyHash = Crypto.ToScriptHash(self.PublicKey.encode_point(True), unhex=True)```
Because `Wallet._keys` stores that same `PublicKeyHash` (see [here](https://github.com/CityOfZion/neo-python/blob/master/neo/Wallets/Wallet.py#L278))
- wrote 2 tests
- ran `python -m unittest discover neo` and did not break anything else.
yes
no
=> Fix Wallet.ContainsKey

scripts/privnet-claim-neo-and-gas.py
Incorrect path in comments for `privnet-claim-neo-and-gas.py`
Updated comment
Just a comment
N/a
Nope
=> Fix comments to show correct location for privnet-claim-neo-and-gas.py

prompt.py
Inaccurate command availability in command hinting.
* Add a new `build` in prompt hint.
* Rename `node` to `nodes` in prompt hint, as `nodes` seems to be the primary command name, while `node` been the alias (for legacy support?).
* Basic smoke test on `prompt.py` against privatenet.
Not Applicable.
No.
=> Update prompt hinting/autocomplete

prompt.py
Display an error message indicating invalid parameter(s) for `wallet` command.
By checking adding a catch all for `item` matching and print out a console message.
Example:
```
neo> wallet sync
wallet: 'sync' is an invalid parameter
```
Basic smoke test on prompt.py against privatenet.
Not Applicable.
No.
=> Add warning message for invalid wallet parameter

neo/VM/ExecutionEngine.py, neo/VM/OpCode.py
Implementing new VM Opcodes recently introduced to the C# VM in this issue:
https://github.com/neo-project/neo/issues/117
This goes along with neo-boa commit https://github.com/CityOfZion/neo-boa/commit/0bb91e754ed575c6a528ff0c469d3ac713eb4085, which provides compiler support for these OpCodes
So... now we can do this in a smart contract:
```
m = [1, 2, 4]
m.reverse()
m.append(8)
Notify(m) # this will output [4,2,1,8]
```
=> add array REVERSE and APPEND VMOp codes

neo/VM/ExecutionEngine.py, neo/VM/OpCode.py
Implementing new VM Opcodes recently introduced to the C# VM in this issue:
https://github.com/neo-project/neo/issues/117
This goes along with neo-boa commit https://github.com/CityOfZion/neo-boa/commit/0bb91e754ed575c6a528ff0c469d3ac713eb4085, which provides compiler support for these OpCodes
So... now we can do this in a smart contract:
```
m = [1, 2, 4]
m.reverse()
m.append(8)
Notify(m) # this will output [4,2,1,8]
```
=> Feature vm additions

neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Implementations/Blockchains/LevelDB/test_LevelDBBlockchain.py
`LevelDBBlockchain.GetBlockHash()` returned invalid values on check failures causing [GetBlock()](https://github.com/CityOfZion/neo-python/blob/aff3e6ca415b45ccb4f6bff9350a60a40e54538a/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L508) and [GetBlockByHeight()](https://github.com/CityOfZion/neo-python/blob/aff3e6ca415b45ccb4f6bff9350a60a40e54538a/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L490) (who rely on the return values) to behave incorrectly.
It now matches the [C# implementation](https://github.com/neo-project/neo/blob/8e1e4f2b91e75c11d35cff3e2607a5fcbf0747ab/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L206) as well 
- It also addresses a typo in …
=>  Fix LevelDBBlockchain.GetBlockHash, add tests + docstrings for affected methods.

neo/Core/TX/ClaimTransaction.py, neo/IO/Helper.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Network/NeoNode.py, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Utils.py, neo/SmartContract/StateReader.py, neo/VM/ExecutionEngine.py, neo/Wallets/Wallet.py, prompt.py
Normalize and correct some console log messages.
Spell correction and minor rewording on some console log messages.
Basic smoke test on prompt.py against privatenet.
Not Applicable.
No.
=> Normalize and correct some console log messages

neo/VM/ScriptBuilder.py
wrong byte written for var int.
correct the byte written
common sense, issue was discussed before for the `BinaryWriter` class
no
no
=> Fix WriteVarInt of ScriptBuilder

prompt.py
Currently when you try to configure an non existing event type, or simply mistype it you'll get a partially confusing error message.
> neo> config sc-evnt on
cannot configure sc-evnt
Try 'config log on/off'
neo> config log on
cannot configure log
Try 'config log on/off'
The "cannot configure <type>" message makes sense, but the one following that suggests you can type `config log on` or `config log off` which you cannot.
I changed the error message to:
`print("Invalid config target: %s", what)`
I believe that without giving a suggestion on what to do next, users will likely try `help` first and see the list of available config commands.
**How did you make sure your solution …
=> Clarify config error message

neo/Implementations/Wallets/peewee/UserWallet.py
the `wallet` command output showed the Address of a wallet in the `script_hash` key instead of the actual scripthash (see below)
```
"addresses": [
{
"votes": [],
"script_hash": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y",
"version": 0,
```
as discussed added both `script_hash` and `address` as key/value pairs
run the test suite + manual testing
no
no
=> correct wallet output for script_hash and address

neo/Blockchain.py, neo/Core/Helper.py, neo/Prompt/Commands/Wallet.py, neo/SmartContract/ContractParameterContext.py, prompt.py
Adds ability to claim gas from neo stored in a smart contract address.
Example below, with SC address hash/address of `c5a6485dc64174e1ced6ac041b6b591074f795e4` and `AeYtu9j8RNDBnBnJ3CrM25Ay2rJAxS5Bkq`:
```
> import contract_addr c5a6485dc64174e1ced6ac041b6b591074f795e4 025688442a89eca1aeed82fab8eded62f93432a155b31c25e9dd1d2c5be2136cf6
> send neo AeYtu9j8RNDBnBnJ3CrM25Ay2rJAxS5Bkq --from-addr=AeYtu9j8RNDBnBnJ3CrM25Ay2rJAxS5Bkq
> wallet claim --from-addr=AeYtu9j8RNDBnBnJ3CrM25Ay2rJAxS5Bkq
```
No
=> adding ability to claim gas from SC address

neo/Settings.py
Address version is hard coded to 23, but is intended to be configurable in protocol.json.
See CityOfZion/neo-python-core#31
Not sure if needed here, see tests in CityOfZion/neo-python-core#31
=> Allow address generation to respect address version from settings

neo/Prompt/Commands/Send.py, neo/Prompt/Commands/tests/test_send_command.py, neo/Prompt/Utils.py
Added ability to include transaction attributes with the `send` command.  example:
`send neo APRgMZHZubii29UXF9uFa6sohrsYupNAvx 10 --tx-attr={'usage':241,'data':'My Remark'}`
-added a parser that looks for the `--tx-attr` flag
- manual and automated testing
- added new tests in `neo/Prompt/Command/tests/test_send_command`
- Transaction attributes are awesome, good way to add meta-data to transactions.  but don't overuse them :)
=> Feature send attrs

neo/Implementations/Wallets/peewee/PWDatabase.py, neo/Implementations/Wallets/peewee/UserWallet.py, prompt.py
- External applications may need to have more than one wallet file open at once.  This change removes the singleton from the `PWDatabase` implementation so that multiple `SQLite` connections can be open at once.
- verified tests
=> Allow multiple open wallet

examples/json-rpc-api-server.py, neo/Settings.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/neo-cli-json-rpc-docs.md, neo/api/JSONRPC/test_json_rpc_api.py, neo/api/REST/NotificationRestApi.py, protocol.coz.json, protocol.mainnet.json, protocol.privnet.json, protocol.testnet.json
`"VersionName": "/NEO-PYTHON:2.3.4/"` was hardcoded in the protocol jsons, i removed it from the jsons and just define it once in settings.py, which will always use the correct current version of neo-python.
Added this to the JsonRpcApi getversion response too.
=> Define VersionName in settings, removed from jsons

neo/Core/Block.py, neo/Core/BlockBase.py, neo/Core/FunctionCode.py, neo/Core/State/AccountState.py, neo/Core/State/AssetState.py, neo/Core/State/ContractState.py, neo/Core/TX/test_transactions.py, neo/Core/test_block.py, neo/IO/Helper.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py, requirements.txt
- upgrade to `neocore` `v.3.2`
- add hex string specifier to all UInt represented in JSON
- fixed how blocks are serialized so that non-verbose blocks can be retrieved from api
- added full transactions into output for blocks
- code
- tests
- tests
- no
=> Localhuman rpc2

neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/neo-cli-json-rpc-docs.md, neo/api/JSONRPC/test_json_rpc_api.py
add `gettxout` RPC call for #189 
add + write tests
make test
yes
changed storage prefix in `GetUnspent()` call from `DBPrefix.ST_SpentCoin` to `DBPrefix.ST_Coin` to make the call functional
yes
feature
=> Add `gettxout` RPC call + tests

neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/SmartContract/test_smart_contract3.py
issue #204 
I called casefold() on the strings before the "__ in __" checks.
I added calls to SearchContract to one of the tests.
yes
no
yes
yes, development
=> make contract search case-insensitive

CHANGELOG.rst, neo/Prompt/InputParser.py, neo/Prompt/test_input_parser.py, prompt.py
Note, this PR is an alternative to the #181 combination, but does not depend on #180.
During the last NEO Meetup, adding a space at the wrong spot would break the current command parser in `prompt.py`, the new implementation is aware of brackets, and quoted strings and should now allow a more natural way of writing lists (like `["arg1", "arg2"...]` instead of forcing us to squash the spaces (ie `["arg1","arg2"...]`).
I've written a parser with `pyparse` which was already an available dependency. Using a proper parser is probably the only way forward for the `prompt.py` language to get more powerful.
I extracted the problematic part …
=> Improved prompt user-input parser

neo/Implementations/Wallets/peewee/test_user_wallet.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
Unless anyone feels strongly otherwise, this should be the final functionality needed in the JSONRPC implementation for us to merge into development.  
- add implementation of `sendrawtransaction`
- tests
- tests
- no 
- yes
=> Localhuman rpc4

CHANGELOG.rst, examples/json-rpc-api-server.py, examples/notification-rest-api-server.py
* Minor bugfixes for the API examples
* CHANGELOG fix: `0.4.7` has not been released, it is still `0.4.7-dev`. For a release, I'd merge dev into master and follow the release steps described at the bottom of the README
=> Minor bugfixes in API examples, CHANGELOG fix

prompt.py
Wallet database isn't closed gracefully during exit, which could potentially lead to database corruption if the database is still open and being written to during shutdown.
Close the wallet before running the rest of the shutdown tasks.
Tested quitting with wallet open and with wallet closed
No
No
Yes
development
=> Gracefully close wallet on exit

bootstrap.py, neo/Core/TX/TransactionAttribute.py, neo/Prompt/Commands/Bootstrap.py, neo/Prompt/Commands/tests/test_bootstrap.py, neo/Settings.py, neo/SmartContract/tests/test_gas_costs.py, neo/VM/ExecutionEngine.py, neo/api/REST/NotificationRestApi.py, neo/api/REST/test_notification_rest_api.py, protocol.coz.json, protocol.mainnet.json, protocol.testnet.json
- updates bootstrap files
- adds ability to download bootstrap notification DB
- fixes issue with TXAttr serialization
- adds tests for bootstrap
- updates home page for notification server
- change notification server page size to 500
- code
- tests
- yes
- if you would like to download the bootstrap data for notifications, you can do that with the `--notifications` flag for the bootstrap command:
```
python bootstrap.py --notifications -m # download notifications for mainnet
python bootstrap.py --notifications # download …
```
=> Feature bootstrap updates

protocol.privnet.json
* Added the missing "NotificationBootstrapFile" key to the privnet config.
```
$ python prompt.py -p
Traceback (most recent call last):
File "prompt.py", line 972, in <module>
main()
File "prompt.py", line 948, in main
settings.setup_privnet()
File "/Users/brian/Projects/Narrative/neo-python2/neo/Settings.py", line 137, in setup_privnet
self.setup(FILENAME_SETTINGS_PRIVNET)
File "/Users/brian/Projects/Narrative/neo-python2/neo/Settings.py", line 117, in setup
self.NOTIF_BOOTSTRAP_FILE = config['NotificationBootstrapFile']
KeyError: 'NotificationBootstrapFile'
```
Added the missing key.
Tested it.
No.
**Are …
=> Added NotificationBootstrapFile for privnet

neo/contrib/smartcontract.py
Event handlers were not being properly isolated between multiple SmartContract instances.
Initialize the event_handlers dictionary in the constructor instead of sharing the dictionary statically across all SmartContract instances.
Tested it. Events were firing multiple times with multiple SmartContracts previously. Now, they only fire for the proper script hash.
No.
No.
Yes, but tests appear to be failing presently on `development`.
**Are you making a PR to a feature branch or development …
=> Fixed bug with SmartContract event handler sharing

neo/VM/ExecutionEngine.py
- push a zero length bytearray onto the stack for PUSH0 instead of a by…tearray with one item of zero
- should resolve the following: https://github.com/CityOfZion/neo-boa/issues/43 https://github.com/CityOfZion/neo-boa/issues/44
- changed `bytearray([0])` to `bytearray(0)`
- tests
- no
- this may change the behavior of how SC operate within `neo-python`.  Where `PUSH0` before pushed `bytearray(b'\x00')` onto the stack, `PUSH0` now pushes `bytearray(b'')`
- this does not affect how the SC would perform within the C# nodes, and this …
=> Zero Length bytearray fix

prompt.py
Errors when quitting prompt (dozens of these):
```
[I 180222 17:17:51 LevelDBBlockchain:539] Could not get block Database is closed 
[I 180222 17:17:51 LevelDBBlockchain:539] Could not get block Database is closed 
```
With traceback:
```
[I 180222 17:21:57 LevelDBBlockchain:540] Could not get block Database is closed 
File "prompt.py", line 977, in <module>
main()
File "prompt.py", line 973, in main
reactor.run()
File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
self.mainLoop()
File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
self.runUntilCurrent()
File …
```
=> Graceful prompt DB shutdown

prompt.py
typo shown when executing the "help" command 
fixed the typo 😺 
ran the prompt and saw the typo is now gone. searched the whole code base for the typo to make sure this is the only place it occured
no
=> fix typo in help output (witdraw -> withdraw)

neo/Wallets/Wallet.py
There are situations where it can be useful to synchronously wait for the wallet rebuild process to complete before returning. We have a script that processes transactions in bulk. It needs to use a wallet to sign the transactions, but sometimes the wallet can become corrupted and result in "insufficient funds" errors. When this happens, we need to rebuild the wallet from a local copy. It's useful to have that rebuild process block until the wallet is fully rebuilt.
https://github.com/NarrativeNetwork/tokensale-neo-smartcontract/blob/master/util/bulk-process-tx.py#L295
Added an optional argument to allow wallet rebuilds be performed synchronously so that `ProcessBlocks` does not …
=> Support Synchronous Wallet Rebuilds

docs/source/install.rst
Add instructions to install it in Ubuntu 17.x where Python 3.5 is not available by using Anaconda.
=> Ubuntu 17.x + Anaconda (python 3.5) installing

api-server.py, neo/api/REST/NotificationRestApi.py
Added a `num_peers` property to the `/status` endpoint of the REST API.
Fixed traceback error for script hash that doesn't exist for `/tokens` endpoint.
Implemented.
Tested.
No.
=> Add num_peers to REST API

README.md, docker/Dockerfile, docker/Dockerfile.dev, docs/source/install.rst
* Updated README.md and docs/install.rst with infos about setting up the new Python 3.6 system, in particular relevant because Ubuntu <16.10 (eg. 16.04, the latest LTS) does not support python-3.6 out of the box.
* Also updated the Docker files
=> Docs for Python 3.6 update

README.md
The readme was still pointing to an old video from somewhere in Q3 2017 with information that (at least partially) doesn't hold anymore. Now updated to the latest and greatest.
change link
clicky click it
no
=> update video link to the latest 0.5 demo video

CHANGELOG.rst, api-server.py, examples/rest-api-server.py, neo/api/REST/RestApi.py, neo/api/REST/test_rest_api.py
RestApi is a more fitting name, because this thing is already evolving to be the standard REST API for notifications and much more ^^
Rename
Test
No
=> Rename NotificationRestApi to RestAPi

CHANGELOG.rst, neo/api/REST/RestApi.py, neo/api/REST/test_rest_api.py
When requesting a block higher than the current block, the API should return `None` for results rather than `[]`.
- code
- added tests
- All requests to the API that are invalid will now receive a `None` for results rather than an empty list `[]`
=> Rest api block height exceeded

Makefile
if a user has a file called `test` in the root directory, then `make test` will always claim its up to date and not run. (it happened to me because I had a wallet called `test`)
add 'test to the phony list
`make test` now works :)
no
Do we add such a minor change to the changelog?
=> Update makefile to phony 'test'

CHANGELOG.rst, prompt.py, protocol.privnet.json, requirements.txt
In prompt.py, added a check if the privnet database is of the same privnet container. An old database is a common error case, without an error message and the only indicator a not increasing block count.
Code
Test
No
=> Privnet chain check

CHANGELOG.rst, neo/api/REST/RestApi.py
Closes CityOfZion/neo-python/#305
`/v1/notifications/addr/<addr>` is now responding.
Now in the right branch hopefully, apologies for the misunderstanding.
=> Fix missing URL in RestApi for address notifications (#305)

CHANGELOG.rst, docs/source/prompt.rst, neo/Prompt/Commands/LoadSmartContract.py, neo/SmartContract/Contract.py, prompt.py
It was unclear how to retrieve NEO TestNet funds using NEO Python as that required a multi-signature contract for which no visible support was present on the prompt. I exposed the `import multisig_addr` command and fixed the `Contract` implementation such that its functional.
write docs & fix code
retrieved my testnet funds and send them to my own wallet address. NEOSCAN confirms it's successful
nah
=> Fix multi-signature contract usage and add NEO TestNet fund retrieval instructions

CHANGELOG.rst, neo/Settings.py, prompt.py
This PR allows `prompt.py` users to specify custom hosts with the `-p` privatenet argument. Useful for instance for events such as hackathons, where people want to connect to the privnet running on a shared server somewhere.
Help output:
$ python prompt.py -h
usage: prompt.py [-h] [-m | -p [host] | --coznet | -c CONFIG]
[-t {dark,light}] [-v] [--version]
optional arguments:
-h, --help            show this help message and exit
-m, --mainnet         Use MainNet instead of the default TestNet
-p [host], --privnet [host]
Use a private net instead of the default TestNet,
optionally using a custom host (default: 127.0.0.1)
--coznet              Use the CoZ network instead of the default TestNet
-c CONFIG, --config …
=> Optionally specifiy custom host with `-p`

.travis.yml, neo/Settings.py, neo/bin/prompt.py
Replaced `os.getcwd()` with proper paths, because using the current working directory can lead to various unwanted edge-cases (like creating a prompt-history file in whatever directory the user currently is in).
Also cleaned up settings paths a little bit.
This is a PR to the other open PR #321.
=> pypi PR minor fixes in Settings and prompt: use proper paths rather than `os.getcwd()`

CHANGELOG.rst, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Tokens.py, neo/SmartContract/tests/test_gas_costs.py, neo/Wallets/NEP5Token.py, neo/bin/prompt.py
#322
Added support for `--from-addr=` parameters for the various invoke methods in both `prompt.py` and other relevant commands.
Tested it. Updated a test to use it.
No.
=> Invoke from address selection

CHANGELOG.rst, neo/SmartContract/StateReader.py
Fixes #324 
By adding TransactionInvocation.GetScript to StateReader.py
Reviewed official StateReader C# implementation as well as other methods in neo-python's StateReader
=> Added TransactionInvocation.GetScript to StateReader.py (fixes #324)

docs/source/settings-and-logging.rst, neo/Settings.py, neo/Wallets/Wallet.py, neo/test_settings.py
* Use `os.path.abspath` to convert paths like `/home/test/.neopython/./Chains` to `/home/test/.neopython/Chains`
* Fix privnet data check path (used old Chains path)
=> Fix settings data paths, privnet path warnings

CHANGELOG.rst, neo/Prompt/Commands/Bootstrap.py
https://github.com/CityOfZion/neo-python/issues/338 - With the new user data paths, the download of the bootstrap files are failing.
Removed the hard-coded relative paths in the bootstrap script and added dynamic user paths based on the new `DATA_DIR_PATH`.
Checked it manually. Downloaded the chains on my personal computer using these changes.
Not really, I just added a call to `os.remove()` on the downloaded file since it isn't removed and stays there wasting space.
=> Update bootstrap script with new paths

CHANGELOG.rst, neo/Prompt/Commands/LoadSmartContract.py, neo/bin/prompt.py
Fixes #301 
By extending the `FileHistory` class to make a custom `History` object that redacts commands before appending them to ``.prompt.py.history`` file when one of the following commands `import wif {wif}`, `export wif {wif}`, `import nep2 {nep2}`, ``export nep2 {nep2}`` are executed. The WIF keys and the nep2 keys are replaced with `<wif>` and `<nep2>` respectively. Metadata (name, description) generated by the command `import contract {path/to/file.avm} {params} {returntype} {needs_storage} {needs_dynamic_invoke}` is also not added to the `.prompt.py.history` file.
I tried running the above specified commands and they are …
=> Fix to redact WIF keys, nep2 keys and contract metadata from the command history file (fixes #301)

neo/Settings.py
Not all users will have a home directory, so only attempt to make the ~/.neopython directory if the user's home directory actually exists. Without this check, startup will fail.
Implemented it.
Tested it on one of our pyapi nodes.
No.
=> Make home directory optional

CHANGELOG.rst, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Commands/Invoke.py, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/tests/test_gas_costs.py
- @MediaServe brought to our attention [this TX](https://neoscan.io/transaction/c20359f4694dd7078f1f3d246430a92ca53d7c1acfc86b602ad9f2eec3fd1b51) which contains 6 transfers of tokens.  After this TX, there is a discrepancy between `neo-python` balance and `neo-cli` balance.  This string of invokes should run out of gas and not persist any changes, but it processes 3 of them and returns as if a successful invoke.
- currently if a smart contract execution encounters errors or runs out of gas, the engine doesn't fail. 
- update `VMState` to `Fault` upon running out of gas or encountering other issues.
- added a test
**Please check the …
=> engine should fail when it runs out of gas

CHANGELOG.rst, neo/Settings.py, neo/SmartContract/tests/test_vm_error_output.py, neo/VM/ExecutionEngine.py, neo/VM/tests/test_interop_map.py
This changes VM fault reporting to only occur when `config debug` (debug logging) is enabled. There's 2 reasons for this;
1) it could help with performance as described in my comment here: https://github.com/CityOfZion/neo-python/issues/352#issuecomment-375582004
2) after the VMFault reporting was added, I saw some users on Discord who thought their neo-python install was broken because they were now notified of the errors that were actually always happening anyway. This should also give them some peace of mind.  
make VM Fault reporting dependent on `setting.log_level`
added a new test case
**Are there any special changes in the …
=> Change VMFault reporting to only output when debug logging is enabled

CHANGELOG.rst, neo/api/JSONRPC/test_json_rpc_api.py, neo/api/utils.py
Adds optional gzip compression if the caller supports it. This feature was recently added here: https://github.com/neo-project/neo/pull/201/commits/6e1921346326e6f89bbca4c39e6123b3eae1c060
update the json decorator used in the RPC server
added a test
nope
=> Add gzip compression support to RPC calls

CHANGELOG.rst, neo/data/protocol.mainnet.json
- adds new bootstrap files for mainnet
- clients/RPC servers should use this bootstrap before proceeding ( or resync from scratch ) otherwise they may be serving/using incorrect data
=> Feature update bootstrap

docker/Dockerfile, docker/README.md, docs/source/basicusage.rst, docs/source/overview.rst, docs/source/prompt.rst
Documentation still points to the old way of starting prompt
Changed prompt.py to np-prompt
It is documentation changes
None
=> Fix document to indicate the new way to start prompt

CHANGELOG.rst, neo/Wallets/Wallet.py
In IsWalletTransaction in neo/Wallets/Wallet.py, as part of evaluating whether a transaction belongs to a wallet or not, neo-python is currently comparing the VerificationScript to all the contract scripthashes in the wallet. However this will never return true, because a scripthash is by definition a hash of a script so it has already gone through the hashing process before the comparison, even if they were the same scripts to start with. As a result, ```wallet verbose``` was not showing the complete set of transactions for added contract addresses and watch-only addresses (outbound transactions were missing)
Changed the comparisons to compare script to script for contracts, and …
=> IsWalletTransaction fix

neo/SmartContract/StateMachine.py
Tested it with my testnet and it works fine after the fix. i could see all the data that was in old-contract in the new-contract and the old-contract was also dropped.
=> #375 Exception during Contract.Migrate

CHANGELOG.rst, neo/api/utils.py
Added a CORS header to fix the JavaScript error `Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`
=> API server: fixed CORS header

CHANGELOG.rst, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Implementations/Wallets/peewee/test_user_wallet.py, neo/Wallets/Wallet.py
When using the `wallet delete_token` command, tokens were removed from the in-memory wallet object but remained in the wallet file, appearing again in memory after the wallet was closed and re-opened. This is because the DeleteNEP5Token function is passed a scripthash instead of a token object, and the wallet db query fails silently while trying to dereference the scripthash from the non-existent object.
I changed the code to pass the NEP5Token object to the db Get function, as a copy was conveniently available as the return from the `super` call right above it.
Tested it manually and also modified the existing import_token unit test …
=> Fix for deleted NEP-5 tokens persisting in wallet file after re-open

neo/Settings.py
When running neo-python with a wrong privnet chain database, the instructions how to remove it were wrong. Simple fix.
=> Privnet error fix

CHANGELOG.rst, neo/VM/InteropService.py, neo/VM/tests/test_interop_serialize.py
- add ability for VM to serialize and deserialize MAP objects
- brings feature parity with C# node according to this: https://github.com/neo-project/neo/pull/215
- code
- added tests
- no
=> Feature add map serialization

CHANGELOG.rst, neo/VM/ExecutionEngine.py, neo/VM/OpCode.py, neo/VM/tests/test_execution_engine.py
- add VERIFY opcode to allow arbitrary verification of pubkey, sig, message 
- brings VM into feature parity with this https://github.com/neo-project/neo-vm/pull/38
- updated ExecutionEngine
- added test
- no
=> add VERIFY opcode to execution engine

CHANGELOG.rst, neo/Prompt/Commands/Tokens.py
when sending tokens the `amount` argument has a rounding error
```
neo> wallet tkn_send PCG1 AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y AZQyxPDwXhiNyvzXx6sLyW1LcbotpeQjp1 0.00000012
Used 3.353 Gas
-----------------------------------------------------------
Will transfer 0.00000011 PCG1 from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to AZQyxPDwXhiNyvzXx6sLyW1LcbotpeQjp1
Transfer fee: 0.0001
-------------------------------------------------------------
```
Note the value difference in "will transfer" from what is specified on the cli
use the `Decimal` class instead of `float`.
manual testing
**Are there any special changes in the code that we should …
=> Fix rounding error for small amounts

CHANGELOG.rst, neo/Core/Blockchain.py
The `Persist()` call in `LevelDBBlockchain.py` loops over the inputs and unnecessary recalculates the `systemshare` every time
https://github.com/CityOfZion/neo-python/blob/ea794abbf941638fbe957d511614f3d66a7c2ef1/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L677
add a small cache
**Before**
> (venv) Eriks-Air:neo-python erik$ python -m timeit -s 'from neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain import LevelDBBlockchain' 'LevelDBBlockchain.SystemShare().Hash.ToBytes()'
10000 loops, best of 3: 130 usec per loop
**After**
> (venv) Eriks-Air:neo-python erik$ python -m timeit -s 'from neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain import …
=> Blockchain Persist performance tweak

neo/SmartContract/StateReader.py
- bring implementation into line with c# ( https://github.com/neo-project/neo/blob/master/neo/SmartContract/StateReader.cs#L485)
- change code
- ran tests
- no
=> fix StateReader.Blockchain_GetContract/GetAsset to bring in line with c#

neo/Core/BlockBase.py, neo/Core/Blockchain.py, neo/Core/Helper.py, neo/Core/TX/ClaimTransaction.py, neo/Core/TX/StateTransaction.py, neo/Core/TX/Transaction.py, neo/Core/test_block_hash.py, neo/Core/test_genesis_block.py, neo/Network/Message.py, neo/Network/Payloads/ConsensusPayload.py, neo/Prompt/Commands/Invoke.py, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/Contract.py, neo/SmartContract/test_contract_parameters.py, neo/VM/ExecutionEngine.py, neo/VM/ScriptBuilder.py, neo/VM/tests/test_execution_engine.py, neo/VM/tests/test_interop_map.py, neo/VM/tests/test_interop_serialize.py, neo/Wallets/Wallet.py
- in some places the star importing brought to the namespace a different package 
e.g, in neo.Core.BlockBase:
from neocore.Cryptography.Helper import *
->
import binascii
from neocore.Cryptography.Helper import bin_dbl_sha256
- in some places the star importing was redundant 
e.g, in neo.Core.Blockchain:
from neocore.Cryptography.Crypto import * 
-> 
∅
- in one place I think the star import is better than explicitly importing all the used objects:
neo.VM.ExecutionEngine
=> Replace import star with explicit imports

CHANGELOG.rst, neo/Core/FunctionCode.py, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Utils.py, neo/bin/prompt.py
- add ability to attach tx attrs to build command and testinvoke.  altered tx attr parsing
- added `invoke_attrs` to various method calls
- ran tests
- you can now do something like `build path/to/avm test 07 01 True False mymethod --tx-attrs=[{'usage':241,'data':bytearray(b'\x01\x02')}]`
- or `testinvoke {hash} mymethod --tx-attrs=[{'usage':241,'data':bytearray(b'\x01\x02')}]`
=> Feature Invoke TX Attrs

CHANGELOG.rst, neo/Prompt/Utils.py, neo/bin/prompt.py
Some string parameters, which can be parsed as float in hex, e.g. `binascii.hexlify(b'anf') == b'616e66'`, are parsed incorrectly.
This PR fixes https://github.com/CityOfZion/neo-python/issues/412
removed unwanted return
I have also added proper (?) formatting to `nodes` command.
I have tried to invoke my contract with 'problem' strings (as well as with normal).
No.
- [-] Did you add any tests?
- [+] Did you run `make lint`?
- [+] Did you run `make test`? (executing right now)
- [+] Are you making a PR to a feature …
=> fix error with string parameter parsing

CHANGELOG.rst, docs/source/install.rst
The instructions to install `neo-python` present on the documentation (`docs` folder) were not up to date. 
I just synced with the `README.rst` so the content is presented in the same (and correct) order, then added the missing `Install from PyPi` section. 
Compiled the sphinx docs and checked
No
**Note**: To make it easier to keep the documentation up to date and avoid duplication, I would suggest that in the future there should be a single source of truth for the documentation. For example, the `README.rst` should point to the docs instead of having install …
=> Update install instructions on the docs

CHANGELOG.rst, neo/bin/api_server.py
RPC and REST endpoints weren't supported in parallel.
Changed it back to the previous implementation so they can both run in parallel.
Tested it.
No.
=> Support RPC and REST in parallel

neo/Wallets/Wallet.py
Just added some documentation about the datatype for Wallet password (see #414)
=> Improved wallet documentation: password aes key (see #414)

CHANGELOG.rst, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/tests/test_token_commands.py, neo/bin/prompt.py
Added a simple version of the transfer history related to a given NEP5 token #162
Added a command to the prompt, that queries the `NotificationDB` for the events related to a given contract. Then extracted the events related to the user's wallet. 
Manually and with simple automated tests. At the moment I still need to solve an issue in my private network (it is unusable -> blocked on a given block) to be able to do more extensive testing. Just submitted so other people can review it, while I try to solve the issue. 
No
**Please check the following, if …
=> NEP5 token transfer history

neo/Implementations/Blockchains/LevelDB/DBCollection.py, neo/Network/NodeLeader.py, neo/SmartContract/StateMachine.py
reset storage state between invocations when an invocation fails.
debugging.
manual review
no
=> fix issue with resetting storages between failed invocations

CHANGELOG.rst, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
Fixes #424.
Emit SC events after the block batch has been committed.
Tested it.
No.
=> Process SC events after write_batch() commit

CHANGELOG.rst, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_claim_command.py, neo/bin/prompt.py
Addresses with thousands of UTXOs may have issues with transaction size preventing GAS claims from working in neo-python.
@localhuman: will be curious to hear your thoughts on this. Does the approach seem reasonable? Necessary? Anything that could be better about it?
Claim GAS for at most 200 UTXOs at a time.
Tested and used the process.
No.
=> High Volume GAS Claim Improvement

CHANGELOG.rst, neo/Core/Block.py, neo/Core/BlockBase.py, neo/Core/TX/ClaimTransaction.py, neo/Core/TX/Transaction.py, neo/Core/test_block.py
As reported by @lucianoengel in Discord #neoscan-api, updated `next_consensus` JSON property to `nextconsensus`. Also completed an audit of the block and transaction JSON to make sure it complies with the C# implementation. This included adding the missing `nonce` property. The primary outstanding issue (which I've documented with todo comments) is to address incorrect size calculations.
Implemented the changes.
Tested it. Added tests to confirm `nonce` and `nextconsensus` are being generated properly.
I need some direction/confirmation on how to address the …
=> RPC JSON Property Tweaks

neo/Prompt/Commands/tests/test_claim_command.py, neo/api/REST/RestApi.py
The error message is inaccurate/confusing in REST API when transaction is not found.
Fixed the handling to deal with tx not found.
Tested.
No.
=> Trivial error change for REST API when transaction is not found

CHANGELOG.rst, neo/Implementations/Notifications/LevelDB/NotificationDB.py, neo/Implementations/Notifications/LevelDB/test_notification_db.py, neo/SmartContract/SmartContractEvent.py
Added mint events to the NotificationDB.
Updated `NotificationDB.py` and `SmartContractEvent.py`
Added a test, but not live tested.
Couldn't get any current mint events on my bootstrapped chains. Is there an easy way to test it, besides on a private net and deploying a NEP-5 SC? (Reminds me, we should a NEP-5 SC to the privatenet default)
No
=> Added mint event type to NotificationDB

CHANGELOG.rst, neo/Settings.py, neo/bin/api_server.py, neo/bin/bootstrap.py, neo/bin/prompt.py
See also #434
In api-server and prompt.py a custom datadir was set after configuring the network. But the network config step checked the datadir. So the datadir needed to be configured before the network.
Updating np-prompt and np-api-server and np-bootstrap
Manual test
No
=> Fix datadir setup

neo/SmartContract/StateReader.py
When a wrong input is passed to CheckWitness (empty byte array, for example) it must FAULT (not return false).
I detected two different executions from python and C#, then I located the source of the problem, a single line.
I tested on Eco platform (neocompiler.io), for both scenarios.
Now it is consistent with the original C# design.
This question is very good! I always forget to put to development branch... :)
=> CheckWitness must FAULT if input is bad

CHANGELOG.rst, neo/contrib/smartcontract.py
Allow SmartContract to use a hash with or without 0x prefix as output by neo-python contract operations.
Check for `0x` prefix and remove it
Manual test
No
=> Allow SmartContract to use a hash with or without 0x prefix

CHANGELOG.rst, requirements.txt
Includes:
* Create wallets with `np-utils --create-wallet`
* `BigInteger(0)` now is `b'\x00'` (PR #50)
=> Update to neo-python-core v0.4.8

CHANGELOG.rst, neo/Core/FunctionCode.py, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Commands/LoadSmartContract.py
- using this in favor of https://github.com/CityOfZion/neo-python/pull/444
- `generate_deploy_script` now expects `BigInteger` for the `ReturnType` paramater
- tests
- no
=> ReturnType is now written by ScriptBuilder as a BigInteger

neo/bin/export.py, neo/bin/import.py
- Renames the file handler variable from `file` to `file_input` and `file_out`.
- Removes unncessary `file.close()` operation, since `with open(..) as x` does that automatically for you
Implement 
Manual test
-
=> Minor import export cleanup

requirements.txt
Interestingly (and not sure how it passed CI), neo-python-rpc was required twice in requirements.txt, once in 0.2.0 and once in 0.2.1
=> Removed double neo-python-rpc requirement

CHANGELOG.rst, neo/Implementations/Wallets/peewee/UserWallet.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py, neo/bin/api_server.py
According to issue https://github.com/CityOfZion/neo-python/issues/189 there are still a few methods missing in the RPC API of `neo-python`. Most of them require an open wallet, a functionality that was missing in the current implementation. 
#428 was later created asking for one of those methods.
Added ``--wallet`` flag to the ``np-api-server`` command. The server can now open a wallet and use it. As a demonstration I also implemented the `listaddress` method, which uses the wallet.
Using a manual testing process plus adding a couple of automated tests.
Not …
=> Add --wallet argument to the api server

CHANGELOG.rst, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
According to the issue https://github.com/CityOfZion/neo-python/issues/189 there are still a few methods missing in the API. This pull request implements `getnewaddress`.
When calling the method on a node with a open wallet, a new address is created.
Manually and with automated tests.
No
=> Add RPC method: "getnewaddress"

CHANGELOG.rst, neo/SmartContract/StateReader.py, neo/VM/tests/test_interop_blockchain.py
- Closes #469 
- add additional interop method
- added tests
- New test in `neo/VM/tests/test_interop_blockchain` could be used as a template to add tests to all interop methods.
=> Add Neo.Blockchain.GetTransactionHeight API

CHANGELOG.rst, neo/api/REST/RestApi.py
The REST API height is always behind by 1 as returned by `/status`.
Added 1 to the return value for consistency with the height checks everywhere else (including in JSON-RPC and other REST API endpoints)
Tested that it always returns the same value as JSON-RPC now.
No.
=> Fixed REST API height always behind by 1

neo/Prompt/Commands/LoadSmartContract.py
Currently we are unable to directly get the address of a multisig contract. This is for ease-of-use for creating custom python programs. 
I added `return address`.
It's a simple, quality of life improvement
Just two words
- [x ] Did you add any tests?
- [x ] Did you run `make lint`?
- [x ] Did you run `make test`?
- [x ] Are you making a PR to a feature branch or development rather than master?
=> return value of address in ImportMultiSigContractAddr()

neo/Settings.py
Fixed the privnet check in settings -- if no privnet is running, now gives proper error message.
n/a
manual test
no
=> Fix privnet check in settings

CHANGELOG.rst, neo/bin/api_server.py
Added process blocks loop for open wallets to np-api-server (see #479)
Adding a task.loopingCall
Manual test
No
=> np-api-server: wallet processblocks loop

CHANGELOG.rst, neo/Core/State/ContractState.py, neo/SmartContract/StateReader.py, requirements.txt
- Even though NEP7 is not implemented/approved yet, many contracts on testnet call the `Neo.Contract.IsPayable` method.  This PR adds that method to the Interop layer, though it will always return False for the moment.
=> Contract payable

README.rst
Adds the instructions to install pycrypto-2.6.1 and fixes spelling errors.
It seems like my update to the readme included some spelling errors. Also, based on other people's comments and conversation in Discord, after uninstalling pycrypto, you should reinstall pycrypto-2.6.1.
=> Readme Update 2

neo/Core/State/ValidatorState.py
Fixes #494 and is a prerequisite to be able to address #427 
Update the class to match the [C# version](https://github.com/neo-project/neo/blob/master/neo/Core/ValidatorState.cs)
Note that I did not add the equivalent of the `ICloneable` interface, as does not seem to be used anywhere in neo-python.
🤞 
For a while I looked into getting some raw data from the C# client that triggers the creation of this class, but I'm not willing to figure out how to create an undocumented `StateTransaction` or how to do an `EnrollmentTransaction` with neo-cli. The edits are so basic that I found it not worth putting that much time in.
**Are there any …
=> Add votes and registered members to ValidatorState class

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/Network/test_node_leader.py, neo/SmartContract/tests/test_migrate_destroy.py, neo/bin/prompt.py, requirements.txt
Update `NodeLeader` peer monitoring system, Add ability to configure size of requests for blocks as well as block processing queue size
You can now set the number of blocks each node request for blocks sends, as well as the total number of blocks to hold in the block processing queue.  To configure manually you can do:
`config node-requests 30 10000` to have each node request 30 blocks at a time and have at most 10k blocks in the processing queue.
You can also use presets `slow/normal/fast` to use values that have been found to be useful: `config node-requests slow`.
Slower node requests are better when block sizes are high ( like during an airdrop) where as fast would be better when syncing the beginning of the chain with mostly empty blocks.
Also adds in `migrate` tests that had been …
=> Update NodeLeader peer monitoring system and configuration

CHANGELOG.rst, docs/source/neo/SmartContract/smartcontracts.rst, examples/smart-contract-rest-api.py, examples/smart-contract.py, neo/contrib/smartcontract.py
* The `SmartContractEvent.event_payload` implementation changed from an array to a `ContractParameter`, which is a breaking change for any event handlers that are introspecting the event data. I've updated all of the docs and examples to work with the updated data type. There already was a note in the CHANGELOG about this change for 0.7.3, so I left that as-is.
* Tweaked some markup issues in the rst docs that I noticed when applying the updates.
Fixes documentation and examples to align with version 0.7.3.
Updates.
Tested the new process in our event handler. …
=> Fixed Docs & Examples for SmartContractEvent.event_payload

CHANGELOG.rst, neo/api/REST/RestApi.py, neo/api/REST/test_rest_api.py
update notification endpoint to include total_pages in output, and allow pagesize paramater to be passed in.  This brings the server in parallel with the C# notification implementation.
Also now page index starts at 1 rather than 0.  Passing in `page=0` will convert to page 1.
- added `total_pages` value to output.
- tests
=> Notification server updates

neo/Network/NeoNode.py, neo/Network/NodeLeader.py, neo/Network/test_node_leader.py
Even after the recent fixes in the development branch to fix the issues in #492, maintaining connection to the peer pool on a long-term basis is still an issue for neo-python in some cases. Often neo-python gets into a state where the peer count will drop to just a few nodes, and no new peers are added after that. Some of the blame may lie on remote nodes incorrectly reporting dead peers as active, a situation neo-python doesn't seem to currently deal well with.
A multi-pronged approach seems to work to improve overall stability of the peer count
:
1. After the initial protocol handshake with a new peer, immediately request its peer list instead of waiting for the timer
2. Track …
=> Improve peer connection maintenance in NodeLeader

CHANGELOG.rst, neo/Prompt/Commands/Send.py, neo/Prompt/Utils.py, neo/Wallets/Wallet.py, neo/bin/prompt.py
- adds ability to attach a fee to a `send` transaction:
`send neo {Addr} {amount} --fee=.0000001`
-manual testing
-no
=> Add ability to attach fee to send tx

CHANGELOG.rst, neo/Core/Block.py, neo/bin/import_blocks.py
Fix #534 
Make block._header accessible and reset header to None after each block commit as a suggested solution by @hal0x2328 
no
- [] Did you run `make test`?
=> Fix block_import script

CHANGELOG.rst, neo/SmartContract/ContractParameterContext.py
I've been seeing this error in travis-ci logs for a while now, figured i'd finally fix it.
```
Transaction initiated, but the signature is incomplete
could not send: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte 
File "/home/travis/virtualenv/python3.6.3/bin/coverage", line 11, in <module>
sys.exit(main())
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/cmdline.py", line 753, in main
status = CoverageScript().command_line(argv)
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/cmdline.py", line 488, in command_line
return self.do_run(options, args)
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/cmdlin …
```
=> Fix ContextItem JSON decode

.github/ISSUE_TEMPLATE.md
There are quite some issues that are being reported where people use an old `neo-python` version. I've added a line asking to first update before reporting. 
I kept the question for writing down in which version the issue happens because reporting might happen while on the latest version (at that point in time) but investigation might happen later on. This way we know ourselves to first test on a later version if we were busy with other higher priority items.
=> Add ISSUE question and direction to first update to latest version

CHANGELOG.rst, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
This PR addresses issue #189 and adds new `getwalletheight` RPC method
Adds similar functionality to https://github.com/neo-project/neo-cli/pull/203
Added two tests
No
=> Add "getwalletheight" RPC method

CHANGELOG.rst, neo/bin/test_prompt.py, requirements.txt
Addresses issue #490
Adds test_prompt.py for testing np-prompt with pexpect
Re-created from https://github.com/CityOfZion/neo-python/pull/536 for to solve compatibility problems
Learned about pexpect, trial and error
Using unittest
Yes, requires installation of pexpect
=> Add test for np-prompt using pexpect

CHANGELOG.rst, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Tokens.py, neo/Wallets/NEP5Token.py
Fix https://github.com/CityOfZion/neo-python/issues/558
One issue was caused by default argument mutation ([read more here](https://docs.python-guide.org/writing/gotchas/))
The other caused by not checking for duplicate scripts before adding them as transaction attributes. Ideally we'd build a transaction via `setters` and have the setter filter for duplicates. Right now I added a separate script. 
I also had to `deepcopy` the `invokeattrs` because they were assigned by reference which caused reusing issues later on. [example location](https://github.com/ixje/neo-python/blob/025d18a7919226685aa9d2c82d3a825eaa11a78a/neo/Prompt/Commands/Invoke.py#L289)
**How did you make sure your …
=> Fix duplicate transaction attributes

requirements.txt
- Fix build issue when running integration tests with neo-core
- remove pycryptodome from `requirements.txt` since it is already in `neocore`
=> update pycryptodome to match neocore version

docs/source/basicusage.rst
I noticed the example for `np-api-server -h` was out of date. I am using this in a tutorial I am writing.
=> Update #view help for `np-api-server`

CHANGELOG.rst, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Wallets/test_wallet.py
- Currently if you open a wallet and let it sync for a while, then close it, it reverts back to the original height if you open it back up again.
- Fix the `SaveStoredData` method to save an existing Key/Value pair properly
- Added a test
- No
=> Fix issue with UserWallet.SaveStoredData

CHANGELOG.rst, requirements.txt
- Makes neo-boa compatible with Python 3.7, so in theory this whole project should now be compatible with Python 3.7
- Should resolve #518 
- Update neo-boa version
=> update neo-boa version

neo/Prompt/Commands/Invoke.py
- After some recent changes, the ability to invoke tx by specifying additional owners was broken.  This fixes that.
=> fix invoke to allow signatures to be added

CHANGELOG.rst, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/tests/test_unclosed_while_loop.py
- Fixes vulnerability to RPC invoke functionality that can send node into unclosed loop during 'test' invokes.
- Limit amount of 'free' operations in application engine to 500k
- Added a test
- No
=> Feature max testops

neo/Network/NeoNode.py
Resolve an exception for #522 
test for `None` return
manual, it threw the error fast when running. now not anymore
no
I think this could be a quick merge just to avoid those that run latest-dev to have errors. Fixing the non-responding incoming peers can be separate. At least that doesn't cause any exceptions
=> resolve peerlist exception

CHANGELOG.rst, neo/Wallets/Wallet.py
- Wallets created after the PeeWee updates have a `MigrationState` of `b'1'` instead of `'1'` as previously, which made it impossible to open a newly created wallet. 
- This change coerces the value to an integer and compares `MigrationState` to `1` so that both versions will work.
- manual testing
- I would not be surprised if there are other similar bugs related to the wallet.
=> Bugfix open newly created wallet

CHANGELOG.rst, neo/Implementations/Wallets/peewee/UserWallet.py
Removes unnecessary notification from `SaveStoredData` as discussed with @localhuman
=> Remove Unnecessary Notification

CHANGELOG.rst, neo/Core/BlockBase.py
import_blocks.py reuses a block object when each new block is read from the chain.acc file, but once a block hash for an block object is requested for the first time, it is cached, so future deserializations of new blocks into the existing object will be associated with the wrong hash.
I added code to `Deserialize` in neo/Core/BlockBase.py to set the private `__hash` variable to `None` before deserializing a new block.
Tested import_blocks.py  - before the change, any imported block would have no transaction results since they were all stored with the wrong hash. After the change, blocks returned the correct list of transactions. …
=> fix for import_blocks.py block hash caching issue

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/data/protocol.mainnet.json, neo/data/protocol.privnet.json, neo/data/protocol.testnet.json
=> resolve simultaneous port usage for #522

CHANGELOG.rst, docs/Readme.rst, docs/source/index.rst, docs/source/install.rst
Updates the `toctree` so all info is displayed on the "readthedocs" website
Recreated from #591 for compatibility issue cc @ixje 
When running `make docs` now, the only warning I receive is:
`WARNING: html_static_path entry '/mnt/c/users/jseag/neo/neo-python-dev/docs/source/_static' does not exist`
I don't think I can eliminate this warning.
Also added instructions for making contributions to neo-python/docs
@localhuman prompted me to run `make docs` then Google to figure out how to update a toctree
Personal Testing
No
**Please check the following, if …
=> Update docs toctree and add instructions for contributing [recreated]

CHANGELOG.rst, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
the C# client supports multiple requests in one call whereas neo-python does not i.e.
```
[
{
"jsonrpc": "2.0",
"method": "getblock",
"params": [1],
"id": 1
},
{
"jsonrpc": "2.0",
"method": "getblock",
"params": [1,1],
"id": 2
}
]
```
add support by detecting list input
add tests
no
It also adds a couple of extra tests to increase the coverage of other calls.
=> Add multi-request JSON-RPC support

CHANGELOG.rst, neo/Network/NeoNode.py
While syncing over the last few days i noticed a couple of malformed network packets resulted in exceptions when trying to deserialize them. 
This pr checks the deserialization results before proceeding and returns otherwise.
no test, just common sense 🤔 
no
=> Gracefully handle network deserialization failure

neo/Core/TX/test_transactions.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/tests/test_bootstrap.py, neo/Utils/BlockchainFixtureTestCase.py, neo/Utils/WalletFixtureTestCase.py, neo/test_preferences.py
There are a couple of tests that didn't work as intended under certain conditions, had uncaught exceptions or otherwise. This cleans up a couple of them
1) This test was passing but internally had an exception that shows up in logs
https://github.com/CityOfZion/neo-python/blob/773e57e72b24a00f6d6d0f9b6fe701e3bb0e7d31/neo/Prompt/Commands/tests/test_send_command.py#L91
2) This test would cause a `404` error on downloading, while actually expected it kept triggering me to look into why. 
https://github.com/CityOfZion/neo-python/blob/master/neo/Prompt/Commands/tests/test_bootstrap.py#L24
3) This test would fail if your configured theme is `light` instead of the default `dark` …
=> Fix a couple of tests 

README.rst
Hopefully addresses: #655 
fix parsing error and change links to be absolute
we're gonna find out now. `rst-lint` throws no errors.
=> Fix parse error in readme, use absolute link format instead of relative

neo/Prompt/Commands/tests/test_send_command.py
Mute an expected stackstrace in a testcase, and clearly identify what throws the exception. Previously one argument was removed from the middle of the list (where arguments all had a default value) causing an type mismatch error. This was not obvious from the test case.
It also seem to prompt me for a password randomly when ran from console.
mock a function to throw an exception
make test
Just a quickfix, not worthy of a changelog, just there to address my clean logs OCD
=> Mute expected test stacktrace 

CHANGELOG.rst, examples/build_raw_transactions.py, neo/Implementations/Wallets/peewee/UserWallet.py
A common question in the #python support channel is how to build raw transactions alá neon-js that can be send over RPC using the `sendrawtransaction` method.
Add a commented file to `\examples\` with 2 examples 1) building a ContractTransaction 2) building an InvocationTransaction
n/a
no
=> Add raw tx building examples

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/Network/test_node_leader.py, neo/api/JSONRPC/test_json_rpc_api.py
Fix #678 
if a peer disconnects or loses connection for whatever reason, then also remove it from the `ADDRS` list, on top of the `Peers` list.
wrote a test pre-fix, failed, fix, works
no
=> Fix getpeers RPC not matching maxpeers

CHANGELOG.rst, neo/Network/NeoNode.py
#687 
Added a `.stop()` to the tasks when cleaning up the disconnected peers.
Tested, problem is resolved
There is currently no reconnection option active, so once disconnected the peer will be gone until restart. This may be a new issue created by fixing the current issue.
=> Fixed #687 cleaning up after disconnected peers

CHANGELOG.rst, neo/Network/NeoNode.py
the looping task for `AskForMoreBlocks` starts multiple times in some cases. this prevents that from happening by not only stopping the deferred call, but also stopping the looping task before restarting it again.
stop running task before starting
manually verifying. previously debug output showed the "ask for more blocks" task (with `maxpeers=1`)  to running up to 3 or 4 times within 10K blocks (on privnet)
no
=> Prevent duplicate looptask

CHANGELOG.rst, neo/Network/NeoNode.py, neo/Network/test_node.py, neo/Network/test_node_leader.py
When data flows in faster than neo-python can process it we eventually hit the max recursion depth of CPython and get a core dump.
instead of using recursion to parse further available data, used a while loop to check if more data exist for parsing
write test first, then solve issue, test no longer crashes the CPython core
no
=> Fix exceeding max recursion depth

CHANGELOG.rst, neo/Core/Block.py, neo/SmartContract/StateReader.py, neo/Wallets/Wallet.py, requirements.txt
- Fix issue with walls of text not allowing syncing of wallets past corrupt blocks.  
- Also removed `Neo.Witness.GetInvocationScript` functionality, closes #695  
- Update to compiler version with `Neo.Witness.GetInvocationScript` functionality removed
- Wallets can now skip corrupt blocks
- Manual tests
- No
=> Wallet sync fix

CHANGELOG.rst, neo/Prompt/Commands/Bootstrap.py, neo/Prompt/Commands/tests/test_bootstrap.py, neo/Settings.py, neo/bin/bootstrap.py, neo/data/protocol.coz.json, neo/data/protocol.mainnet.json, neo/data/protocol.testnet.json, neo/data/protocol.unittest-net.json, requirements.txt
- Fix the dreaded `cannot join current thread` people are now getting with `np-bootstrap` https://github.com/CityOfZion/neo-python/issues/700
- each time bootstraps are updated people need to update their protocol config files
- downgraded to the previous `tqdm==4.23.4` that doesn't have this issue
- make `bootstrap.py` query what the latest files are via a `bootstrap_latest` json file looking like this:
```
{
"mainnet": "https://s3.us-east-2.amazonaws.com/cityofzion/bootstrap_main/Main292952.tar.gz ",
"mainnet_notif": "https://s3.us-east-2.amazonaws.com/cityofzion/bootstrap_main/MainNotif292952.tar.gz",
"testnet": "https://s3.us-east-2.amazonaws.com/cityofzion/bootstrap_main/Test …
```
=> Bootstrap fix + updates

CHANGELOG.rst, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/SmartContractEvent.py, neo/VM/ExecutionEngine.py, neo/VM/InteropService.py, neo/VM/tests/test_interop_map.py, neo/bin/prompt.py
When people deploy faulty smart contracts on the blockchain or commit transactions that talk to them in the wrong way then errors can be thrown in the console. There's a good group of users that look at this log output and think their `neo-python` install is malfunctioning or broken. To list some examples:
> [W 181107 08:37:51 SmartContractEvent:278] Writing Payload value amount greater than ulong long is not allowed. Setting to ulong long max
> [E 181107 08:37:47 ApplicationEngine:233] NOT ENOUGH ITEMS TO CONCAT
> [I 181107 08:41:51 InteropService:190] Trying to get big integer Array [..omitted..]
> [I 181107 08:41:58 LevelDBBlockchain:383] Could not find transaction for hash b'insert hash'
**How did you solve …
=> Silence - change logging levels on certain parts

CHANGELOG.rst, neo/Core/State/AccountState.py, neo/Prompt/Commands/tests/test_send_command.py, neo/api/JSONRPC/test_json_rpc_api.py
This pull request tries to fix https://github.com/CityOfZion/neo-python/issues/713
Changed the JSON serialization of the AccountState instances
Tested manually and updated the automatic test
No, I do think I fixed it everywhere, but something might be missing.
=> Fix response schema of the "getaccountstate" RPC method 

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/Prompt/Commands/Send.py, neo/SmartContract/ContractParameterContext.py, neo/Wallets/Wallet.py, neo/bin/prompt.py
There are a bunch of issues with signing using a multi-signature account
- calling `sign` without a wallet throws an exception
- calling `sign` without having the multi-signature address in the wallet silently fails with a non-related message `relaying tx failed`
- The `CHECKMULTISIG` operation failed because public key and signature pairs where mismatched on the stack 'non-deterministic' (e.g. pubkey_a was compared with signature_c, pubkey_b with signature_a, etc)
2 other errors also solved while working on it
- when sending assets from `wallet_a` and then quickly opening `wallet_b` left a ghost thread running that tried to update Coin references that only existed in `wallet_a` causing exceptions.
- if a …
=> Fix various issues related to signing with multi-signature addresses 

CHANGELOG.rst, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
This pull request completes the `getpeers` RPC functionality. At the time of the implementation, `neo-python` didn't track bad peers so it wasn't able to provide that information, since then that functionality was added so we must update the RPC method.
Added `bad` peers based on the `DEAD_ADDRS` list on the `NodeLeader`.
Updated the `getpeers` test
No
=> Added bad addresses to getpeers RPC endpoint

CHANGELOG.rst, neo/Settings.py
a warning about default bootstraps was given when not applicable. fixed logic
running the terminal myself
=> Fix default bootstrap warning

CHANGELOG.rst, neo/Settings.py, neo/Utils/plugin.py, neo/api/JSONRPC/JsonRpcApi.py, neo/bin/api_server.py, neo/data/protocol.mainnet.json, neo/data/protocol.privnet.json, neo/data/protocol.testnet.json, neo/data/protocol.unittest-net.json
A different approach for loading plugins as suggested in #699, Django inspired
add a class loader
manually run `api_server.py` with Rest and RPC servers
Yes; the `RPC_SERVER` and `REST_SERVER` variables are now stored at module level and not part of the `SettingsHolder` class. The implication is that all networks (main/test/priv) use the same settings. The alternative is moving it into the `SettingsHolder` which means we need to update all `protocol.xxx.json` files to include new keys to load from and otherwise have a sane default.
What approach would be …
=> Initial Django inspired component loading

neo/Prompt/CommandBase.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_send_command.py, neo/Prompt/Commands/tests/test_wallet_commands.py, neo/Prompt/PromptData.py, neo/bin/prompt.py
- supports https://github.com/CityOfZion/neo-python/issues/623
- adds support for `wallet` `send`, `sendmany`, `sign`, `open`, and `close`
manual testing. I haven't added coverage yet.
**-update-**
I added coverage for `send` and `sendmany`. Let me know what you think.
No. But please check my implementation to see if I am on the right track.
=> Add support for `wallet` `send`, `sendmany`, `sign`, `open`, and `close`

neo/Prompt/CommandBase.py, neo/Prompt/Commands/Wallet.py, neo/bin/prompt.py
1. `help`, `quit` and `exit` being handled outside of `CommandBase` feature, the words were unknown from the autocompleter.
2. `CommandWalletCreateAddress.command_desc` was missing a aparameter.
1. Add these words to the autocompletion words list.
2. Added the parameter
Manual test.
No.
=> [refactor-prompt] Prompt fixes

neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Prompt/Commands/Search.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_search_commands.py, neo/bin/prompt.py
- Reference https://github.com/CityOfZion/neo-python/pull/737
- This PR supports the `search` method group (see https://github.com/CityOfZion/neo-python/issues/623#issuecomment-443991459
Unittest
=> [refactor prompt] Add support for search method group

neo/Prompt/Commands/Search.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_show_commands.py, neo/bin/prompt.py
- Reference https://github.com/CityOfZion/neo-python/pull/737
- This PR supports the first five methods from the `show` method group (see https://github.com/CityOfZion/neo-python/issues/623#issue-362278030)
Unittest
No
=> [refactor prompt] Add support for show method group (pt 1)

neo/Network/NodeLeader.py, neo/Utils/BlockchainFixtureTestCase.py
Related to https://github.com/CityOfZion/neo-python/pull/740#discussion_r239346845
`NodeLeader` was not reset between test cases.
This would lead to some problems when the blockchain is reset but the `NodeLeader` instance members are not, especially `NodeLeader.KnownHashes` and `MemPool`.
Transactions were still considered as known.
1. Add missing members in `NodeLeader.Setup()`
2. Call `NodeLeader.Instance().Setup()` in `BlockchainFixtureTestCase.setUpClass()`
3. Also removed the unsued member `NodeLeader.MissionsGlobal`
Unit tests succeed.
Note: maybe this …
=> Fix NodeLeader was not reset between test cases.

CHANGELOG.rst, neo/Prompt/Commands/Invoke.py, neo/Wallets/NEP5Token.py, neo/bin/prompt.py
Say you have a wallet with "custom token x", that you've been developing on your network. If you switch network (e.g. to mainnet or a place that does not have that token) and try to use `wallet` to view the contents it will throw a flurry of exceptions. 
apply error checking, print a useful error message.
`make test`
`test_invoke` now returns an additional boolean indicating the VM execution status
=> Gracefully handle NEP-5 balance query failures

neo/Core/Blockchain.py, neo/Core/FunctionCode.py, neo/Core/State/ContractState.py, neo/Core/TX/test_transactions.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Implementations/Blockchains/LevelDB/test_LevelDBBlockchain.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/tests/test_show_commands.py, neo/SmartContract/ContractParameterType.py, neo/SmartContract/SmartContractEvent.py, neo/api/JSONRPC/test_json_rpc_api.py, neo/bin/prompt.py
- Reference https://github.com/CityOfZion/neo-python/pull/737
- This PR supports the last five methods from the `show` method group (see https://github.com/CityOfZion/neo-python/issues/623#issue-362278030)
Unittest
- `ShowAllAssets` was added so `show assets` mirrors `show contracts`
- originally implemented here https://github.com/CityOfZion/neo-python/pull/667
- Added the ability to use 'neo' or 'gas' to show the corresponding assets
-  originally implemented here https://github.com/CityOfZion/neo-python/pull/667
**Please check the following, …
=> [refactor prompt] Add support for show method group (pt 2)

neo/Implementations/Wallets/peewee/UserWallet.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
Migrate the command `wallet delete_addr` to the new Command system.
Implementation of `CommandWalletDeleteAddress`
Added unit tests & manual testing
Not a change but `UserWallet.DeleteAddress` always returns True so even when using `wallet delete_addr unknown_address`, the prompt output is `Deleted address unknown_address`.
If we want to change this behaviour, let's discuss the details.
=> [refactor-prompt] Migrate command: wallet delete_addr

neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
Migrate the command `wallet alias` to the new Command system.
Implementation of `CommandWalletAlias`
Added unit tests & manual testing
No
=> [refactor-prompt] Migrate command: wallet alias

neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_token_commands.py, neo/Prompt/Utils.py, neo/Wallets/NEP5Token.py, neo/Wallets/Wallet.py
move #623 forward by adding `token history`
port to new command
make test
Yes. When I added the `get_token` utility function in `neo.Prompt.Utils` I was facing circular import errors. To get around them I changed some import statements to not import functions directly, but import the module and call from there. 
=> [refactor-prompt] add wallet token history

neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
move #623 forward by implementing `wallet export nep2` and `wallet export wif` commands.
write code
make test
Yes the old prompt required you to enter your wallet password multiple times before you could export. This was mostly a protection on the cli level but didn't really unlock anything as the wallet is already open with the keys useable. Now the prompt instantly exports without asking for input. 
=> [refactor-prompt] add wallet export commands

neo/Implementations/Wallets/peewee/UserWallet.py, neo/Implementations/Wallets/peewee/test_user_wallet.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
Move #623 forward by implementing `wallet import watch_addr`. 
write code
make test
no
=> [refactor-prompt] add wallet import watchaddr

neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/tests/test_token_commands.py
move #623 forward
migrate and refactor code
tests
no
=> [refactor-prompt] add token approve and token allowance

neo/Prompt/Commands/Config.py, neo/Prompt/Commands/tests/test_config_commands.py
move #623 forward by
migrate
make test
no
=> [refactor-prompt] add config nep8

neo/Core/Helper.py, neo/Core/State/AssetState.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Network/Message.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py, neo/SmartContract/Contract.py, neo/Wallets/Wallet.py, neo/logging.py
#623 
Migrate the command `wallet split` to the new `Command` system.
Implementation of `CommandWalletUnspent`
manual testing
Add unit tests 
No
=> [refactor-prompt] Migrate command: wallet split

neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
#623 
Migrate the command `wallet import token` to the new `Command` system.
Implementation of `CommandWalletImportToken`
unit tests & manual testing
No
=> [refactor-prompt] Migrate command: wallet import token

neo/Prompt/Commands/LoadSmartContract.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/tests/test_wallet_commands.py
#623 
Migrate the command `wallet import contract_addr` to the new `Command` system.
Implementation of `CommandWalletImportContractAddr`
unit tests
In `Wallet.py`, I moved `_is_valid_public_key` out of `CommandWalletImportMultisigAddr` and put it into global space. Please tell me if it is to avoid.
=> [refactor-prompt] Migrate command: wallet import contract_addr

neo/Prompt/Commands/Config.py, neo/Prompt/Commands/Search.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/WalletAddress.py, neo/Prompt/Commands/WalletExport.py, neo/Prompt/Commands/WalletImport.py, neo/Prompt/Commands/tests/test_config_commands.py, neo/Prompt/Commands/tests/test_token_commands.py, neo/Prompt/Commands/tests/test_wallet_export_commands.py, neo/Prompt/Commands/tests/test_wallet_import_commands.py
1) some group commands had the error message 
```
Please specify an action. See help for available actions
```
the other half
```
run `<cmd name> help`   to see supported queries
```
2) A good part of the commands used
```
Please specify the required parameters
```
others use slightly more specific
```
Please specify the <missing argument name>
```
and then some had completely different responses like
```
invalid number of   arguments
Not enough   arguments
etc
```
3) some commands that toggle settings accepted either `1` or `on`, others accepted more boolean values like `t`, `true` etc.
streamline responses amongst commands for certain actions. see commits
**How did you make …
=> [refactor-prompt] cleanup 2

neo/Prompt/Commands/SC.py, neo/Prompt/Commands/tests/test_sc_commands.py
move #623 forward by adding `sc debugstorage`
port & update, write tests
make test
no
=> [refactor-prompt] add debugstorage command

neo/Prompt/Commands/Config.py, neo/Prompt/Commands/SC.py, neo/Prompt/Commands/Search.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/WalletAddress.py, neo/Prompt/Commands/WalletExport.py, neo/Prompt/Commands/WalletImport.py
- some parameter help descriptions used the form of `the <something>` and `a <something>` whereas others just stated `<something>`
- some descriptions had typo's, unnecessary long names, vague descriptions or inconsistent descriptions
streamline all the above to use the same format
n/a
no
=> [refactor-prompt] cleanup parameter descriptions

neo/Prompt/Commands/WalletExport.py, neo/Prompt/Commands/tests/test_wallet_export_commands.py
In https://github.com/CityOfZion/neo-python/pull/780 (and another PR) we discussed if we should be prompted for the wallet password before we can send funds. The question has been posted on slack and after some thought I think that at least from the cli it should be asked for. Currently for exporting keys this is not asked
This PR introduces wallet password checking before exporting the key 
tests
=> [refactor-prompt] update export cmds with password checking

neo/Prompt/CommandBase.py
@jseagrave21 pointed out a problem with `show state help` here: https://github.com/CityOfZion/neo-python/pull/788#pullrequestreview-189586441
Test for available params before attempting to print them (where a `max()` received an empty input)
manual testing on the console
no
=> [refactor-prompt] fix exception in specific help case 

neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/tests/test_token_commands.py
In #780 (and another PR) we discussed if we should be prompted for the wallet password before we can send funds. The question has been posted on slack and after some thought I think that at least from the cli it should be asked for. 
Previously we could bypass it using a `--ask_for_pw` type of flag. While the logic remains in some parts of the code (so people can programmatically choose), from the CLI it is no longer possible to bypass for security reasons.
remove optional arg to bypass
make test
no
=> [refactor-prompt] enforce pw prompt send

neo/Prompt/CommandBase.py, neo/Prompt/Commands/BuildNRun.py, neo/Prompt/Commands/Config.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/LoadSmartContract.py, neo/Prompt/Commands/SC.py, neo/Prompt/Commands/Search.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/Tokens.py, neo/Prompt/Commands/Wallet.py, neo/Prompt/Commands/WalletAddress.py, neo/Prompt/Commands/WalletExport.py, neo/Prompt/Commands/WalletImport.py, neo/Prompt/Commands/tests/test_claim_command.py, neo/Prompt/Commands/tests/test_config_commands.py, neo/Prompt/Commands/tests/test_output_config.py, neo/Prompt/Commands/tests/test_sc_commands.py, neo/Prompt/Commands/tests/test_search_commands.py, neo/Prompt/Commands/tests/test_send_command.py, neo/Prompt/Commands/tests/test_show_commands.py, neo/Prompt/Commands/tests/test_token_commands.py, neo/Prompt/Commands/tests/test_wallet_commands.py, neo/Prompt/PromptPrinter.py, neo/Prompt/Utils.py, neo/bin/prompt.py
resolve the following todo of #623 
> after the previous item, make sure console themes still work. This requires "Format Tokens" from the prompt_toolkit package, but it should only be applied when used in the CLI. Meaning; the business logic should not be coupled to a PromptInterface() instance because that's the one who creates the theme tokens. solution idea: supply print function as param.
replace built-in print with `prompt_print` in the classes below `Commands` as follows:
```
from neo.Prompt.PromptPrinter import prompt_print as print
```
This was the most straight forward way to replace all `print` calls in command code. One advantage is that we can easily swap out the …
=> [refactor-prompt] restore theming support

neo/Prompt/CommandBase.py, neo/Prompt/Commands/Wallet.py
@jseagrave21 pointed out an issue with `wallet help` here: https://github.com/CityOfZion/neo-python/pull/788#pullrequestreview-189586838
LysanderGG gave alternative solutions to resolve it, here: https://github.com/CityOfZion/neo-python/pull/788#issuecomment-451644553
option 1 was implemented for the time being because as pointed out by LysanderGG, only 1 command currently needs it. When we encounter multiple use-cases we can get a better feel of the requirements and adjust accordingly.
manual testing. it now shows
```
neo> wallet help
Usage: wallet COMMAND (or "wallet" to show the wallet contents)
Manage wallets
```
**Are there any …
=> [refactor-prompt] update wallet usage help

neo/Implementations/Wallets/peewee/test_user_wallet.py, neo/Network/test_node_leader.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/tests/test_send_command.py, neo/Wallets/Wallet.py, neo/api/JSONRPC/JsonRpcApi.py
Currently whenever you try to send assets with insufficient funds you get the following output
```
neo> wallet send NEO AG4Z3kNtdQxDvdCPYyht1Mq8ntdi7uHuvy 25
[E 190105 12:16:44 Wallet:1071] insufficient funds for asset id: c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b
[D 190105 12:16:44 Send:233] insufficient funds
neo>
```
A double error message, and also one that doesn't always clearly identify the real reason. The above account had more than enough funds, but not enough `vouts`
Changed the error handling of `MakeTransaction` such that we can differentiate the root cause. The above scenario now shows
```
neo> wallet send NEO AG4Z3kNtdQxDvdCPYyht1Mq8ntdi7uHuvy …
```
=> [refactor-prompt] polish and clarify insufficient funds reason

neo/Prompt/PromptPrinter.py
we proxy/wrap `print` data to `prompt_toolkits`'s `print_formatted_text`. The latter asserts the inputs and we didn't handle lists (and possible other objects) in the way it expects. 
Ensure all data are strings
manual test the error case reported in DM on slack.
no
=> [refactor-prompt] fix prompt printer for lists types

CHANGELOG.rst, neo/Wallets/Wallet.py
fix #801 
correctly calculate the total paid that gets subtracted from the `vin` to form the change amount.
manual testing
=> Fix change value calculation when using alternating asset inputs

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/Network/utils.py, neo/data/protocol.testnet.json
the current testnet seeds in `protocol.testnet.json` are not working anymore.
re-introduce named seeds and a bit of code to translate the hostname to ip addresses in nodeleader.
test
=> Fix testnet seeds

CHANGELOG.rst, neo/Network/NodeLeader.py, neo/Utils/BlockchainFixtureTestCase.py
A common root cause for tests failing to relay is because NodeLeader isn't reset properly. Other tests could have created a similar TX which is now stored in the `KnownHashes` and therefore `Relay` fails.
add reset logic
make test and faced this issue again when merging `development` into #723 
no
=> properly reset NodeLeader for test cases

CHANGELOG.rst, neo/Implementations/Wallets/peewee/Models.py
peewee prints
```
neo-python/venv/lib/python3.6/site-packages/peewee.py:235: DeprecationWarning: "PrimaryKeyField" has been renamed to "AutoField". Please update your code accordingly as this will be completely removed in a subsequent release.
warnings.warn(s, DeprecationWarning)
```
follow suggestion of peewee
make test, manually open old wallet.
no
=> Resolve Peewee deprecation warning

CHANGELOG.rst, neo/VM/ExecutionEngine.py, requirements.txt
Update VM as like https://github.com/neo-project/neo-vm/pull/71/
add `SafeReadBytes` to neocore and create a new release, update ExecutionEngine
make test
=> VM safereadbytes

CHANGELOG.rst, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
add https://github.com/neo-project/neo/pull/541
add code
write tests
no
=> Add gettransactionheight RPC method

CHANGELOG.rst, neo/Network/NeoNode.py, neo/Prompt/Commands/Show.py, neo/Prompt/Commands/tests/test_show_commands.py
The current output of show nodes is a bit messy. It's not aligned, has some irrelevant info and missing relevant info. This is a little improvement to clean that up (ported from the `network_improv` branch)
old
```
neo> show node
Total Connected: 3
Peer IPv4Address(type='TCP', host='127.0.0.1', port=20333) - IO: 0.000322 MB in / 0.000211 MB out
Peer IPv4Address(type='TCP', host='127.0.0.1', port=20334) - IO: 0.000347 MB in / 0.000211 MB out
Peer IPv4Address(type='TCP', host='127.0.0.1', port=20334) - IO: 8.7e-05 MB in / 0.000211 MB out
```
new
```
neo> show node
Total Connected: 3
Peer 0  /NEO:2.8.0/ -       127.0.0.1:20333 - IO   0.000346 MB in /   0.000211 MB out
Peer 1  /NEO:2.8.0/ -       127.0.0.1:20334 - IO …
```
=> cleanup show nodes output

neo/Wallets/Wallet.py, neo/bin/prompt.py
1) #751 introduced a bug for deploying smart contracts. The fee calculated in `MakeTransaction` was off due to the change and could cause an "insufficient funds" error. This resolves that.
2) the prompt showed a block and header height that was consistently 1 ahead of the reality. I discovered this while being connected to a local `neo-cli` node. This would also give a bad user experience as people would try to query the latest block and get a "block not found" (which is true as it didn't exist yet).
1) remove sysfee multiplication. Also doesn't exist in the neo-cli reference code
2) remove the `+1` in the prompt toolbar (not sure why that was ever there)
**How did you make sure …
=> Fix sysfee maketx / block height display

CHANGELOG.rst, neo/Wallets/Wallet.py, neo/bin/prompt.py
Monitoring wallet height requires getting all the wallet info which can be slow depending on how many address/tokens/contracts exist in the wallet
Added the current wallet height to the bottom toolbar in the same format neo-cli uses (wallet height/db height/blockchain height)
Manual testing
No
=> Add wallet height to bottom toolbar

CHANGELOG.rst, neo/Prompt/Commands/SC.py, neo/Prompt/Commands/tests/test_sc_commands.py, neo/Prompt/Utils.py
Contract invocation results are displayed using the default return type of the contract, even though some operations will return different types than the default, requiring the user to manually convert results, e.g. from bytearray to integer
Added a --return-type argument to the `sc invoke` command to allow the user to override the contract's default return type during a test invoke
Manual testing
No
=> add --return-type to override test invoke return parameter type

neo/SmartContract/Contract.py
In order to update the VM we had to change the implementation of `ReadVarBytes` to use [SafeReadBytes](https://github.com/CityOfZion/neo-python-core/blob/0e27b796d962385e52451ee20c2258c47d9e6e8c/neocore/IO/BinaryReader.py#L70) in this [PR](https://github.com/CityOfZion/neo-python-core/pull/178) on neo-python-core . This however breaks tests like (being one of)
https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/neo/Wallets/test_wallet.py#L124-L126
Because a `Contract()` is created and saved in the DB where the `script` member length is determined by a `b'aabbcc'` data `script` member whereas reading back data for `script` (during deserialization) gives `b'\xaa\xbb\cc` data …
=> Lock contract deserialize to old ReadVarBytes implementation

CHANGELOG.rst, neo/SmartContract/tests/test_sc_debug_events.py, neo/SmartContract/tests/test_vm_error_output.py, neo/Utils/VMJSONTestCase.py, neo/VM/ExecutionEngine.py, neo/VM/InteropService.py, neo/VM/tests/test_interop_map.py
https://github.com/neo-project/neo-vm/pull/98
write code
run VM test vectors
no
=> Add PICKITEM for ByteArray into VM

CHANGELOG.rst, neo/Core/Fixed8.py, neo/Core/tests/test_io.py, neo/Core/tests/test_numbers.py, neo/Prompt/Commands/tests/test_send_commands.py, neo/api/JSONRPC/test_json_rpc_api.py
fix #940
change `ToString()`
make test
=> Align Fixed8 string output representation with C#

CHANGELOG.rst, neo/bin/export_blocks.py, neo/bin/import_blocks.py
- Both `np-import` and `np-export` could try to register a blockchain without properly deregistering the existing one.
- the `np-import` script was setup to call 
https://github.com/CityOfZion/neo-python/blob/e7e57e5d3d9b3e859dfe39140361343a8f3b94e8/neo/bin/import_blocks.py#L21
but because that is a co-routine it would fail. This fixes that issue such that `np-import` can be run again, along side `python neo/bin/import_blocks`
- `np-import` was modified for speed to persist blocks directly and once done update the header list. This actually causes issues with smart contract execution. Specifically smart contracts that request block data (e.g. to get the timestamp) will fail. Reason being is that the code will call …
=> Fix np-import/export

CHANGELOG.rst, neo/Core/TX/Transaction.py, neo/Prompt/Commands/Send.py
- resubmitting https://github.com/ixje/neo-python/pull/17
- addresses https://github.com/CityOfZion/neo-python/pull/934#issuecomment-496112217
- searched for logzero imports
- replaced with `log_manager` where necessary: Transaction.py & Send.py
- completed manual testing to verify expected result
manual testing
**NOTE:** I don't think I can add individual unittests for this issue because running `make test` displays every level of `logger`.
no
=> fix undesired debug statement printing

CHANGELOG.rst, neo/Network/nodemanager.py
- addresses https://github.com/CityOfZion/neo-python/pull/934#pullrequestreview-231428364 and https://github.com/CityOfZion/neo-python/pull/934#pullrequestreview-243522758
- now points to `settings.NODE_PORT` instead of `8888`
manual testing
no
=> revert nodemanager.start.port

CHANGELOG.rst, neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
fix https://github.com/CityOfZion/neo-python/issues/951
convert negative lshift into positive rshift and negative rshift into positive lshift.
added tests cmparing against C# output
=> Fix BigInteger bitwise shifting behaviour

CHANGELOG.rst, neo/Prompt/Commands/Config.py, neo/Prompt/Commands/tests/test_config_commands.py
**NOTE**: updated re-submission of https://github.com/ixje/neo-python/pull/12
- update for `minpeers`
- update for errors when the new `maxpeers` < connected peers
- update tests
- update to set `minpeers` equal to `maxpeers` if `maxpeers` < `minpeers`
- specifically, when new `maxpeers` < connected peers
- fixes a RuntimeError caused by calling a coro in another loop
- see https://github.com/ixje/neo-python/pull/12#pullrequestreview-231447541
- fixes an error where the same node was disconnected multiple times
- see https://github.com/ixje/neo-python/pull/12/files/7292761e76ac3a983dbbfc85b41b0b9ef406cbb7..be1307860d274b0db82b3eaf06ff6cb37037350b
- updates tests
**How did you …
=> Fix `config maxpeers`

CHANGELOG.rst, neo/Implementations/Wallets/peewee/UserWallet.py, neo/Prompt/Commands/tests/test_address_commands.py
- resubmitting https://github.com/ixje/neo-python/pull/18
- addresses https://github.com/CityOfZion/neo-python/pull/934#issuecomment-496112560
- if an alias exists for the address, print the alias
- updated tests
**NOTE:** Right now there is no ability within neo-python to update/delete the alias once it is set. I think this should be a future feature update.
manual testing initially and `make test` after tests were updated
no
=> include alias in pretty print

CHANGELOG.rst, neo/Prompt/Utils.py
when running sc invocations via e.g. the `build_run` command we parse the smart contract parameters from the console. Specifically list arguments were trouble some. Take
```
sc build_run sc.py False False False 0210 01 1 ['aa']
```
The old logic would parse `['aa']` into a BigInteger because 
https://github.com/CityOfZion/neo-python/blob/d2362d4de3e278da7fe7dd68a07d798053a1f7bd/neo/Prompt/Commands/Invoke.py#L509
would turn `['aa']` into `[b'6161']` because it uses recursion internally.
Then when we continue we parse the items again in which 
https://github.com/CityOfZion/neo-python/blob/d2362d4de3e278da7fe7dd68a07d798053a1f7bd/neo/Prompt/Commands/Invoke.py#L510-L514
which now tries to parse `[b'6161']` and that …
=> Fix prompt list parsing

CHANGELOG.rst, neo/SmartContract/StateMachine.py, neo/SmartContract/StateReader.py, requirements.txt
The ongoing audit showed a deviation in gas consumption for Testnet block 449841. 
Both `RunTime.Trigger` and `Transaction.GetType` are supposed to push integers to the stack, neo-python pushed bytes. For the majority of time this worked well, but the mentioned block showed a contract where a `NUMEQUAL` instruction would fail the comparison in `neo-python` whereas `neo-cli` passed. This caused the next instruction `JMPIFNOT` to take a different branch and the rest is history. 
pushing int's instead of bytes.
audit of the block now passes (=gas consumption equals neo-cli)
**Are there any special changes in the code that we should be …
=> Fix Runtime.Trigger and Transaction.GetType syscalls

CHANGELOG.rst, neo/SmartContract/tests/test_vm_error_output.py, neo/VM/ExecutionEngine.py, neo/VM/tests/test_interop_map.py
audit of block testnet block 460271 showed a deviation in VMState. The root cause is a difference in handling types that are not of type Array or Map.
fix the default handling to match C#
block now passes with the same results as neo-cli
=> changing PICKITEM handling of invalid type

CHANGELOG.rst, neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
the audit of testnet block `678752` showed a storage deviation caused by a difference in return value for the `BigInteger.ToByteArray()` method for the number `-48335248028225339427907476932896373492484053930`
glanced at the C# source of the `BigInteger` class and applied somewhat similar logic
test cases + audit now passes for the block
=> fix BigInteger.ToByteArray() for certain negative values

CHANGELOG.rst, neo/bin/import_blocks.py
when we supplied the `-a` flag for appending blocks, the code would still deserialise all data
skip block deserialization and move the file pointer directly to the next block until we've reached the current height
manual testing
=> Speedup np-import when appending blocks

CHANGELOG.rst, neo/SmartContract/StateMachine.py, neo/SmartContract/StateReader.py, neo/VM/InteropService.py
The audit of testnet block `620999` showed that the `GetInterface()` method of `InteropService` didn't do anything when it comes to checking subclassing of the specified type. This caused some interop methods to pass validation where they should have failed resulting in deviating VM behaviour.
Update the method to use type information
audit of the above block now passes
=> Fix InteropService.Getinterface not validating types

CHANGELOG.rst, neo/Core/TX/Transaction.py, neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py
Audit of testnet block `697324` showed a deviation in VM result stack return value due to an incomplete TX deserialization routine. 
The stack item reported a 
```
{"type: "Interop", "value": "Transaction"}
```
Instead of
```
{"type: "Interop", "value": "ContractTransaction"}
```
fix deserialization to use correct TX class for ContractTransaction
audit now passes for block
n/a
=> Fix tx deserialization class for ContractTransaction

CHANGELOG.rst, neo/Core/IO/BinaryWriter.py, neo/VM/InteropService.py
audit of testnet block `735309` showed a deviating in VMState due to a wrong type returned by `StackItem.Boolean.GetBigInteger()` causing an exception.
fix to actually return a BigInteger instead of an int.
audit passes for the block
=> Fix boolean StackItem return type for `GetBigInteger()`

neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
audit of testnet block `784078` showed that the fixes we applied in #963 were not all encompassing/incorrect. This now handles both cases and also fixes incorrect old tests
see code
audit passes
=> Fix BigInteger again

CHANGELOG.rst, neo/SmartContract/StateMachine.py
audit of testnet block `846536` showed a deviating in VMstate due to the syscall `Neo.Contract.Create` accepting invalid `ContractParameterType`'s whereas `neo-python` throwed exceptions. The issue is reported there: https://github.com/neo-project/neo/issues/827
added a workaround to be inline with `neo-cli`, but should be fixed in `neo-cli`
audit passes, make test
na/
=> Workaround neo-cli accepting invalid contract parameter types

CHANGELOG.rst, neo/SmartContract/StateReader.py, neo/Storage/Interface/DBInterface.py
Audit of TestNet block `936671` showed a deviating in storage due to incorrect state being committed in the previous block while the TX failed. It was not committed in the actual run of the faulty TX, but because the DBInterface was not properly cleared from its state the next successful commit included the changes from the faulty TX.
DBCollection/DBInterface now properly resets all state when the TX failed.
audit now passes for the block and all blocks leading up to it
=> Fix dbcollection not properly clearing state for faulty TXs

CHANGELOG.rst, neo/SmartContract/StateMachine.py, neo/SmartContract/StateReader.py, neo/Storage/Implementation/LevelDB/LevelDBCache.py
Audit of testnet block `1303979` shows a deviation in Storage changes. 
- the existing syscall `System.Runtime.GetTime` implementation uses the latest already persisted block to get the timestamp from. C# instead uses the currently being persisted block. This led to a 1 byte difference in the script to be migrated, causing a different script_hash and as a result storages could not be found properly.
- Contract_Migrate and Contract_Destroy operated on the wrong provided key data. The key data was supplied in reversed byte order causing it to not find existing storages.  
fix the above 2 items
audit now passes, make test still ok, …
=> Fix Contract_Migrate syscall

CHANGELOG.rst, neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
Audit of testnet blocks `1474198`  and `1474514` showed a deviation in gas consumption. After backtracking this was caused by pushing a different result by the `MOD` instruction. This then led to a `LT` comparison between a negative vs positive value, whereas C# compared a positive + positive value which happened to be `false` in the C# case and `true` in Python's case. That resulted in deviating behaviour for the `JMPIFNOT` that followed and the rest is self-explanatory.
The deviation occurs due to Python's different way of handling negative divisor values.
handle negative case different
audit now passes
**Are there any special …
=> Fix bigint3 modulo

CHANGELOG.rst, neo/VM/InteropService.py
audit of testnet block `1532382` showed a deviation in gas consumption due to a different return value for the `GetBoolean()` call of the `Array` stack item.
bring inline with changes to C#
audit passes, make test
=> fix Array.GetBoolean()

neo/SmartContract/StateMachine.py, neo/SmartContract/StateReader.py, neo/Storage/Common/DataCache.py
- audit of testnet block `1546918` showed a deviation in VMState due to incorrect handling of duplicate results from the DataCache + Internal storage. Internal storage only returns the actual `key` value, whereas the DataCache holds `contract_hash + key` values for looking up. 
- various testnet blocks showed error logs regarding various Serialization/Deserialization issues. I investigated 2 cases (Runtime_Serialize and Runtime_Deserialize) of respectively blocks `1552947` and `1553029` and concluded that the behaviour is inline with C# neo-cli. The error message is too aggressive possible leading to user confusion whether it's a real problem or not
- audit of testnet block `1575282` showed a deviation in VMState …
=> fix DataCache duplicate results + invalid Contract return type handling

neo/SmartContract/StateMachine.py
while https://github.com/CityOfZion/neo-python/pull/978 fixed Contract return type validation for the block at hand, it broke a historical validation. When using Python enums a ValueError is thrown when trying to create an enum from an invalid value
e.g.
```python
class MyEnum(Enum):
bla = 0x1
t1 = MyEnum(1) # OK
t2 = MyEnum(2) # raises ValueError
```
In C# it actually doesn't care as long as the value you're trying to cast fits in the datatype (in the case of ContractParameter a `byte`). In #978 the return_type value was 2 bytes and failed to cast to a 1 byte enum in C#. The solution used for that block was ok, but fails for block `846536`. This PR resolves that.
change …
=> update contract return type verification

CHANGELOG.rst, neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
audit of testnet block `1473972` showed a deviation in storage due to a different rounding used for C# compared to neo-python when dividing 2 BigIntegers where the dividend is negative. Specifically `-11001000000` / `86400` should result in `-127326` but resulted in `-127327`.
change divide logic
audit for the block passes, other tests still pass, added a couple more tests for which I took the expected values from a C# program.
=> fix BigInteger divide

neo/SmartContract/StateMachine.py
testnet block `1701573` sets up a `ByteArray` type with `0xF0` as data on the evaluation stack for the return type of a `Contract_Create` call. This should be equal to the `InteropInterface` type, however it seems that neo-cli expects `0x00F0` because they convert to `BigInteger` which is signed. Therefore we're getting `-16` and that should fail. 
don't allow negative numbers for the type
audit for the block now passes
=> further tighten return type checking

CHANGELOG.rst, neo/SmartContract/ApplicationEngine.py
audit of testnet block `1729953` showed a deviation in gas consumption due to a difference in handling invalid contract properties in the  `GetPriceForSysCall()` function compared to neo-cli. Where neo-cli throws an exception when trying to cast the contract property to a `byte`, neo-python did not and happily continued. 
apply similar logic as in #982
audit of block now passes
=> fix price check call for Neo.Contract.Create

neo/Core/Blockchain.py, neo/Utils/BlockchainFixtureTestCase.py
Explicitly defining `lambda` for account syncing to fix `TypeError: 'AccountState' object is not callable` errors.
Added `lambda`, per @ixje.
Tested before and after. Errors happening before; syncing works after.
No.
=> Fixed AccountState Sync Issue

CHANGELOG.rst, neo/VM/InteropService.py
Audit of testnet block `2053221` showed a deviation in VM execution due to different ways of handling the removal of non-existing items in the `Map` and `Array` types.
C# returns a boolean False if the item is not found in its dictionary/list, Python by default throws KeyError or ValueError respectively. This caused neo-python to fail VM execution, whereas C# would continue
add try/catch and return bool for found status
audit now passes
=> Fix Remove() for Map/Array VM types

CHANGELOG.rst, neo/SmartContract/ApplicationEngine.py, neo/SmartContract/StateReader.py, neo/VM/ExecutionEngine.py, neo/VM/InteropService.py
audit of testnet block `2105805` showed a deviation in VM state due to no support for compressed syscalls. neo-python would throw an exception on compressed syscall operands
add support for compressed format
audit of the block now passes
no
=> Add support for compressed syscall

CHANGELOG.rst, neo/Prompt/Commands/Tokens.py
* Fixed a bug where sending NEP-5 tokens via the Prompt CLI did not properly handle the NEP-5 decimal conversion. Thus, previously, you'd have to enter the amount as a "raw" value without a decimal in order for the proper amount of tokens to be sent.
Added the proper conversion of the user-entered decimal amount to the raw value based on the NEP-5 token's `decimals`. This fix is mirrored off of the `approve` command, which was already handling the conversion properly.
Tested it.
No.
=> Fix Prompt Bug with Sending NEP-5 Tokens

neo/SmartContract/Iterable/StorageIterator.py, neo/SmartContract/StateMachine.py, neo/Storage/Common/DataCache.py, neo/Storage/Implementation/LevelDB/LevelDBCache.py
`Storage.Find` did not work properly when called after storage was altered in the current snapshot. This would cause it to not find data in it's cache and return duplicate results and also in the wrong order.
=> fix storage find iterator when facing cached data

neo/Core/BigInteger.py, neo/Core/tests/test_numbers.py
Add new tests for a block that failed. Change implementation to use `Decimal` % thanks to @merl
see above
=> add biginteger tests + mod change

CHANGELOG.rst, neo/VM/ExecutionEngine.py
Audit of testnet block `2431844` showed a deviation in gas consumption due to a difference in the `NOT`  VM instruction. The faulty implementation would throw an exception because we tried to get a `BitInteger` from a `Map` VM type, which isn't possible. 
align implementation
audit of block now passes
=> fix NOT VM instruction

CHANGELOG.rst, neo/VM/InteropService.py
audit of testnet block `2591458` showed a deviation in storage value due to wrong a deserialization of a Boolean VM type. This was caused by the Boolean type receiving an `integer` as value as opposed to a `bool` type. This resulted in deserializing the value `44` as opposed to `True`, leading to a `0x01 0x2c` instead of  `0x01 0x01`.
convert int to bool for stack item deserialization
audit of block passes
=> fix stack item deserialization for Boolean VM type

CHANGELOG.rst, neo/SmartContract/ApplicationEngine.py
audit of testnet block `2606285` showed a deviation in VM state due to the `CheckDynamicInvoke` function not using snapshots and accessing the data caching layer. 
make it use snapshots
audit of the block now passes
=> update dynamic invoke check to use snapshots

CHANGELOG.rst, neo/SmartContract/StateReader.py
audit of testnet block `2644593` showed that the `Contract.Destroy` SYSCALL would under certain conditions not delete all contract storage.
fix key data lookup input for internal storage call of the DataCache
audit of the said block now passes
=> fix contract destroy storage deletion

CHANGELOG.rst, neo/VM/InteropService.py
Audit of Testnet block `2728887` showed a deviation in gas consumption due to failed comparison between a single element `ByteArray` and an integer. 
ensure that the `Equals` method of `ByteArray` tries to compare against another `ByteArray` type instead of whatever type it might be.
audit of the block now passes
=> Fix ByteArray equals

neo/SmartContract/ApplicationEngine.py
audit of testnet block `2842737` showed a deviation in VM state due to not using snapshots for CALL_ED/EDT dynamic invoke validation. This should have been part of #995 
use same logic as #995
audit of block passes
=> use snapshot for ED/EDT validation

neo/bin/api_server.py, neo/bin/prompt.py
the `sc config maxpeers/minpeers` command already has a 10 peers max limit imposed. The cli arguments did not. 
add argument choices limit
manual testing. now gives the following error if a wrong argument is given
```
np-api-server: error: argument --maxpeers: invalid choice: 12 (choose from 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```
=> limit cli maxpeers

CHANGELOG.rst, neo/Core/TX/Transaction.py, neo/Core/Utils.py, neo/Implementations/Wallets/peewee/test_user_wallet.py, neo/Network/nodemanager.py, neo/Prompt/Commands/Invoke.py, neo/Prompt/Commands/Send.py, neo/Prompt/Commands/tests/test_sc_commands.py, neo/Prompt/Commands/tests/test_send_commands.py, neo/Wallets/Wallet.py, neo/api/JSONRPC/JsonRpcApi.py, neo/api/JSONRPC/test_json_rpc_api.py
Addresses #960; specifically, https://github.com/CityOfZion/neo-python/issues/960#issuecomment-512248474
implement SimplePolicy check when relaying any tx
- results in a cancelled tx and a required fee recommendation if SimplePolicy requirements are not met
- addresses https://github.com/CityOfZion/neo-python/issues/960#issuecomment-512248474 by checking each tx after it is signed
`make test` with unittests
Replaced `TXFeeError` with `TXError` to incorporate a check for violating the tx maximum size
=> Fix simple policy implementation for outgoing transactions

CHANGELOG.rst, neo/VM/ExecutionEngine.py
audit of mainnet block `3602763` showed a deviation in gas consumption due to an incorrect implementation of the `RIGHT` VM opcode. The existing JSON tests also do not cover this.
A `0` count operand should result in an empty buffer, the existing implementation used `buffer[-count:]` which worked fine as long as the count > 0. For the specific case of `0` it would actually return the full buffer instead of an empty buffer as needed. This would return incorrect lenghts, causing an `LT`->`JMPIF` sequence to point the IP to the wrong next instruction.
fix implementation to be explicit. Also addressed possible issue with similar logic for the `LEFT` instruction.
**How did you make …
=> fix RIGHT and LEFT VM opcodes

docker/Dockerfile
docker uses python 3.6, whereas the latest version will only work with 3.7
install 3.7
ran
```
docker build --no-cache -f Dockerfile -t neopython .
```
and passed
=> update docker to use python 3.7

.travis.yml, requirements.txt
travis and the install requirements were still pointing at github commits due to a missing neo-boa release.
reached out to neo-boa author to push a new release to pypi
manual testing
=> use neo-boa from pypi

CHANGELOG.rst, neo/Prompt/PromptData.py, neo/bin/api_server.py
Partially addresses https://github.com/CityOfZion/neo-python/issues/1020, specifically issues 1-3. Now, the program will automatically exit whenever an issue arises when opening a wallet or setting minpeers/maxpeers.
I haven't figured out how to solve issue 4 from https://github.com/CityOfZion/neo-python/issues/1020.
(-edit-) All issues from https://github.com/CityOfZion/neo-python/issues/1020 have been addressed thanks to input from @ixje 
I replaced applicable instances of `return` with `raise SystemExit` which had precedence for issues setting `port-rpc` and `port-rest`.
Manual testing
**Are there any special changes in the code …
=> np-api-server auto exit

CHANGELOG.rst, neo/Network/nodemanager.py
A recent discussion on slack showed that an edge case can exist in which `neo-python` runs out of node address to fill our desired connection slots and cannot recover. In such a scenario `neo-python` recycles all addresses it ever learned over the network (both bad and good) and tries to find a working node. There is a threshold on how long it tries before recycling again. This threshold is time based, not address list exhaustive. The recycling logic always produces the same list, therefore if the first `n` addresses in the list are bad, we can hit the time threshold and recycle before finding a good node.   
We randomize the addresses just after recycling them. This should …
=> Minor update to network recovery

CHANGELOG.rst, neo/Core/Cryptography/ECCurve.py, neo/Core/KeyPair.py
There are 5 syntax warnings in 2 files in the current code. Warnings appear when neo-python is installed as a library in a separate project.
`SyntaxWarning: "is not" with a literal. Did you mean "!="?`
Replaced them with `!=` which is the proper way to compare literals.
It doesn't raise syntax warning anymore. 
no
=> Fix to the syntax warnings caused by comparing literals
